/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A function affected by changes to the target.
 * @export
 * @interface AffectedFunction
 */
export interface AffectedFunction {
    /**
     * File path relative to repository root.
     * @type {string}
     * @memberof AffectedFunction
     */
    file: string;
    /**
     * Name of the affected function.
     * @type {string}
     * @memberof AffectedFunction
     */
    name: string;
    /**
     * Line number of the function declaration.
     * @type {number}
     * @memberof AffectedFunction
     */
    line?: number;
    /**
     * Type of code element.
     * @type {string}
     * @memberof AffectedFunction
     */
    type: AffectedFunctionTypeEnum;
    /**
     * Number of hops from the target in the call graph.
     * @type {number}
     * @memberof AffectedFunction
     */
    distance: number;
    /**
     * Relationship type to the target.
     * @type {string}
     * @memberof AffectedFunction
     */
    relationship: AffectedFunctionRelationshipEnum;
}


/**
 * @export
 */
export const AffectedFunctionTypeEnum = {
    Function: 'function',
    Method: 'method',
    Class: 'class'
} as const;
export type AffectedFunctionTypeEnum = typeof AffectedFunctionTypeEnum[keyof typeof AffectedFunctionTypeEnum];

/**
 * @export
 */
export const AffectedFunctionRelationshipEnum = {
    DirectCaller: 'direct_caller',
    TransitiveCaller: 'transitive_caller'
} as const;
export type AffectedFunctionRelationshipEnum = typeof AffectedFunctionRelationshipEnum[keyof typeof AffectedFunctionRelationshipEnum];


/**
 * Check if a given object implements the AffectedFunction interface.
 */
export function instanceOfAffectedFunction(value: object): value is AffectedFunction {
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('distance' in value) || value['distance'] === undefined) return false;
    if (!('relationship' in value) || value['relationship'] === undefined) return false;
    return true;
}

export function AffectedFunctionFromJSON(json: any): AffectedFunction {
    return AffectedFunctionFromJSONTyped(json, false);
}

export function AffectedFunctionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AffectedFunction {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'],
        'name': json['name'],
        'line': json['line'] == null ? undefined : json['line'],
        'type': json['type'],
        'distance': json['distance'],
        'relationship': json['relationship'],
    };
}

export function AffectedFunctionToJSON(value?: AffectedFunction | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file': value['file'],
        'name': value['name'],
        'line': value['line'],
        'type': value['type'],
        'distance': value['distance'],
        'relationship': value['relationship'],
    };
}

