/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A file affected by changes to the target.
 * @export
 * @interface AffectedFile
 */
export interface AffectedFile {
    /**
     * File path relative to repository root.
     * @type {string}
     * @memberof AffectedFile
     */
    file: string;
    /**
     * Number of direct dependencies in this file.
     * @type {number}
     * @memberof AffectedFile
     */
    directDependencies: number;
    /**
     * Number of transitive dependencies in this file.
     * @type {number}
     * @memberof AffectedFile
     */
    transitiveDependencies: number;
}

/**
 * Check if a given object implements the AffectedFile interface.
 */
export function instanceOfAffectedFile(value: object): value is AffectedFile {
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('directDependencies' in value) || value['directDependencies'] === undefined) return false;
    if (!('transitiveDependencies' in value) || value['transitiveDependencies'] === undefined) return false;
    return true;
}

export function AffectedFileFromJSON(json: any): AffectedFile {
    return AffectedFileFromJSONTyped(json, false);
}

export function AffectedFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): AffectedFile {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'],
        'directDependencies': json['directDependencies'],
        'transitiveDependencies': json['transitiveDependencies'],
    };
}

export function AffectedFileToJSON(value?: AffectedFile | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file': value['file'],
        'directDependencies': value['directDependencies'],
        'transitiveDependencies': value['transitiveDependencies'],
    };
}

