/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An entry point affected by changes to the target.
 * @export
 * @interface AffectedEntryPoint
 */
export interface AffectedEntryPoint {
    /**
     * File path relative to repository root.
     * @type {string}
     * @memberof AffectedEntryPoint
     */
    file: string;
    /**
     * Name or route of the entry point.
     * @type {string}
     * @memberof AffectedEntryPoint
     */
    name: string;
    /**
     * Type of entry point.
     * @type {string}
     * @memberof AffectedEntryPoint
     */
    type: AffectedEntryPointTypeEnum;
}


/**
 * @export
 */
export const AffectedEntryPointTypeEnum = {
    RouteHandler: 'route_handler',
    ModuleExport: 'module_export',
    MainFunction: 'main_function',
    EventHandler: 'event_handler'
} as const;
export type AffectedEntryPointTypeEnum = typeof AffectedEntryPointTypeEnum[keyof typeof AffectedEntryPointTypeEnum];


/**
 * Check if a given object implements the AffectedEntryPoint interface.
 */
export function instanceOfAffectedEntryPoint(value: object): value is AffectedEntryPoint {
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function AffectedEntryPointFromJSON(json: any): AffectedEntryPoint {
    return AffectedEntryPointFromJSONTyped(json, false);
}

export function AffectedEntryPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): AffectedEntryPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'],
        'name': json['name'],
        'type': json['type'],
    };
}

export function AffectedEntryPointToJSON(value?: AffectedEntryPoint | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file': value['file'],
        'name': value['name'],
        'type': value['type'],
    };
}

