/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A code element with active callers or references.
 * @export
 * @interface AliveCodeItem
 */
export interface AliveCodeItem {
    /**
     * File path relative to repository root.
     * @type {string}
     * @memberof AliveCodeItem
     */
    file: string;
    /**
     * Name of the function, class, or method.
     * @type {string}
     * @memberof AliveCodeItem
     */
    name: string;
    /**
     * Line number where the declaration starts.
     * @type {number}
     * @memberof AliveCodeItem
     */
    line: number;
    /**
     * Type of code element.
     * @type {string}
     * @memberof AliveCodeItem
     */
    type: AliveCodeItemTypeEnum;
    /**
     * Number of unique callers or references.
     * @type {number}
     * @memberof AliveCodeItem
     */
    callerCount: number;
}


/**
 * @export
 */
export const AliveCodeItemTypeEnum = {
    Function: 'function',
    Class: 'class',
    Method: 'method',
    Interface: 'interface',
    Type: 'type',
    Variable: 'variable',
    Constant: 'constant'
} as const;
export type AliveCodeItemTypeEnum = typeof AliveCodeItemTypeEnum[keyof typeof AliveCodeItemTypeEnum];


/**
 * Check if a given object implements the AliveCodeItem interface.
 */
export function instanceOfAliveCodeItem(value: object): value is AliveCodeItem {
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('line' in value) || value['line'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('callerCount' in value) || value['callerCount'] === undefined) return false;
    return true;
}

export function AliveCodeItemFromJSON(json: any): AliveCodeItem {
    return AliveCodeItemFromJSONTyped(json, false);
}

export function AliveCodeItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): AliveCodeItem {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'],
        'name': json['name'],
        'line': json['line'],
        'type': json['type'],
        'callerCount': json['callerCount'],
    };
}

export function AliveCodeItemToJSON(value?: AliveCodeItem | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file': value['file'],
        'name': value['name'],
        'line': value['line'],
        'type': value['type'],
        'callerCount': value['callerCount'],
    };
}

