/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Blast radius metrics for a target.
 * @export
 * @interface BlastRadius
 */
export interface BlastRadius {
    /**
     * Number of direct callers/dependents.
     * @type {number}
     * @memberof BlastRadius
     */
    directDependents: number;
    /**
     * Number of transitive (indirect) dependents.
     * @type {number}
     * @memberof BlastRadius
     */
    transitiveDependents: number;
    /**
     * Number of files affected.
     * @type {number}
     * @memberof BlastRadius
     */
    affectedFiles: number;
    /**
     * Domains affected by this change (scaffolded, empty in v1).
     * @type {Array<string>}
     * @memberof BlastRadius
     */
    affectedDomains?: Array<string>;
    /**
     * Risk level based on blast radius analysis.
     * @type {string}
     * @memberof BlastRadius
     */
    riskScore: BlastRadiusRiskScoreEnum;
    /**
     * Human-readable explanations for the risk score.
     * @type {Array<string>}
     * @memberof BlastRadius
     */
    riskFactors?: Array<string>;
}


/**
 * @export
 */
export const BlastRadiusRiskScoreEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Critical: 'critical'
} as const;
export type BlastRadiusRiskScoreEnum = typeof BlastRadiusRiskScoreEnum[keyof typeof BlastRadiusRiskScoreEnum];


/**
 * Check if a given object implements the BlastRadius interface.
 */
export function instanceOfBlastRadius(value: object): value is BlastRadius {
    if (!('directDependents' in value) || value['directDependents'] === undefined) return false;
    if (!('transitiveDependents' in value) || value['transitiveDependents'] === undefined) return false;
    if (!('affectedFiles' in value) || value['affectedFiles'] === undefined) return false;
    if (!('riskScore' in value) || value['riskScore'] === undefined) return false;
    return true;
}

export function BlastRadiusFromJSON(json: any): BlastRadius {
    return BlastRadiusFromJSONTyped(json, false);
}

export function BlastRadiusFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlastRadius {
    if (json == null) {
        return json;
    }
    return {
        
        'directDependents': json['directDependents'],
        'transitiveDependents': json['transitiveDependents'],
        'affectedFiles': json['affectedFiles'],
        'affectedDomains': json['affectedDomains'] == null ? undefined : json['affectedDomains'],
        'riskScore': json['riskScore'],
        'riskFactors': json['riskFactors'] == null ? undefined : json['riskFactors'],
    };
}

export function BlastRadiusToJSON(value?: BlastRadius | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'directDependents': value['directDependents'],
        'transitiveDependents': value['transitiveDependents'],
        'affectedFiles': value['affectedFiles'],
        'affectedDomains': value['affectedDomains'],
        'riskScore': value['riskScore'],
        'riskFactors': value['riskFactors'],
    };
}

