/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CircularDependencyResponse } from './CircularDependencyResponse';
import {
    CircularDependencyResponseFromJSON,
    CircularDependencyResponseFromJSONTyped,
    CircularDependencyResponseToJSON,
} from './CircularDependencyResponse';

/**
 * 
 * @export
 * @interface CircularDependencyResponseAsync
 */
export interface CircularDependencyResponseAsync {
    /**
     * Current status of the job.
     * @type {string}
     * @memberof CircularDependencyResponseAsync
     */
    status: CircularDependencyResponseAsyncStatusEnum;
    /**
     * Unique identifier for the job.
     * @type {string}
     * @memberof CircularDependencyResponseAsync
     */
    jobId: string;
    /**
     * Recommended seconds to wait before polling again.
     * @type {number}
     * @memberof CircularDependencyResponseAsync
     */
    retryAfter?: number;
    /**
     * Error message (present when status is failed).
     * @type {string}
     * @memberof CircularDependencyResponseAsync
     */
    error?: string;
    /**
     * 
     * @type {CircularDependencyResponse}
     * @memberof CircularDependencyResponseAsync
     */
    result?: CircularDependencyResponse;
}


/**
 * @export
 */
export const CircularDependencyResponseAsyncStatusEnum = {
    Pending: 'pending',
    Processing: 'processing',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type CircularDependencyResponseAsyncStatusEnum = typeof CircularDependencyResponseAsyncStatusEnum[keyof typeof CircularDependencyResponseAsyncStatusEnum];


/**
 * Check if a given object implements the CircularDependencyResponseAsync interface.
 */
export function instanceOfCircularDependencyResponseAsync(value: object): value is CircularDependencyResponseAsync {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    return true;
}

export function CircularDependencyResponseAsyncFromJSON(json: any): CircularDependencyResponseAsync {
    return CircularDependencyResponseAsyncFromJSONTyped(json, false);
}

export function CircularDependencyResponseAsyncFromJSONTyped(json: any, ignoreDiscriminator: boolean): CircularDependencyResponseAsync {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'jobId': json['jobId'],
        'retryAfter': json['retryAfter'] == null ? undefined : json['retryAfter'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : CircularDependencyResponseFromJSON(json['result']),
    };
}

export function CircularDependencyResponseAsyncToJSON(value?: CircularDependencyResponseAsync | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'jobId': value['jobId'],
        'retryAfter': value['retryAfter'],
        'error': value['error'],
        'result': CircularDependencyResponseToJSON(value['result']),
    };
}

