/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Summary statistics for the circular dependency analysis.
 * @export
 * @interface CircularDependencyMetadata
 */
export interface CircularDependencyMetadata {
    /**
     * Total number of files in the dependency graph.
     * @type {number}
     * @memberof CircularDependencyMetadata
     */
    totalFiles: number;
    /**
     * Total number of import relationships.
     * @type {number}
     * @memberof CircularDependencyMetadata
     */
    totalImports: number;
    /**
     * Number of cycles found.
     * @type {number}
     * @memberof CircularDependencyMetadata
     */
    cycleCount: number;
    /**
     * Algorithm used for cycle detection (e.g., tarjan_scc).
     * @type {string}
     * @memberof CircularDependencyMetadata
     */
    analysisMethod: string;
    /**
     * Timestamp when analysis started.
     * @type {Date}
     * @memberof CircularDependencyMetadata
     */
    analysisStartTime?: Date;
    /**
     * Timestamp when analysis completed.
     * @type {Date}
     * @memberof CircularDependencyMetadata
     */
    analysisEndTime?: Date;
}

/**
 * Check if a given object implements the CircularDependencyMetadata interface.
 */
export function instanceOfCircularDependencyMetadata(value: object): value is CircularDependencyMetadata {
    if (!('totalFiles' in value) || value['totalFiles'] === undefined) return false;
    if (!('totalImports' in value) || value['totalImports'] === undefined) return false;
    if (!('cycleCount' in value) || value['cycleCount'] === undefined) return false;
    if (!('analysisMethod' in value) || value['analysisMethod'] === undefined) return false;
    return true;
}

export function CircularDependencyMetadataFromJSON(json: any): CircularDependencyMetadata {
    return CircularDependencyMetadataFromJSONTyped(json, false);
}

export function CircularDependencyMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CircularDependencyMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'totalFiles': json['totalFiles'],
        'totalImports': json['totalImports'],
        'cycleCount': json['cycleCount'],
        'analysisMethod': json['analysisMethod'],
        'analysisStartTime': json['analysisStartTime'] == null ? undefined : (new Date(json['analysisStartTime'])),
        'analysisEndTime': json['analysisEndTime'] == null ? undefined : (new Date(json['analysisEndTime'])),
    };
}

export function CircularDependencyMetadataToJSON(value?: CircularDependencyMetadata | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'totalFiles': value['totalFiles'],
        'totalImports': value['totalImports'],
        'cycleCount': value['cycleCount'],
        'analysisMethod': value['analysisMethod'],
        'analysisStartTime': value['analysisStartTime'] == null ? undefined : ((value['analysisStartTime']).toISOString()),
        'analysisEndTime': value['analysisEndTime'] == null ? undefined : ((value['analysisEndTime']).toISOString()),
    };
}

