/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Aggregate summary of circular dependency analysis.
 * @export
 * @interface CircularDependencySummary
 */
export interface CircularDependencySummary {
    /**
     * Total number of cycles found.
     * @type {number}
     * @memberof CircularDependencySummary
     */
    totalCycles: number;
    /**
     * Number of unique files involved in at least one cycle.
     * @type {number}
     * @memberof CircularDependencySummary
     */
    filesInCycles: number;
    /**
     * Number of high-severity cycles.
     * @type {number}
     * @memberof CircularDependencySummary
     */
    highSeverityCount: number;
    /**
     * Number of medium-severity cycles.
     * @type {number}
     * @memberof CircularDependencySummary
     */
    mediumSeverityCount: number;
    /**
     * Number of low-severity cycles.
     * @type {number}
     * @memberof CircularDependencySummary
     */
    lowSeverityCount: number;
}

/**
 * Check if a given object implements the CircularDependencySummary interface.
 */
export function instanceOfCircularDependencySummary(value: object): value is CircularDependencySummary {
    if (!('totalCycles' in value) || value['totalCycles'] === undefined) return false;
    if (!('filesInCycles' in value) || value['filesInCycles'] === undefined) return false;
    if (!('highSeverityCount' in value) || value['highSeverityCount'] === undefined) return false;
    if (!('mediumSeverityCount' in value) || value['mediumSeverityCount'] === undefined) return false;
    if (!('lowSeverityCount' in value) || value['lowSeverityCount'] === undefined) return false;
    return true;
}

export function CircularDependencySummaryFromJSON(json: any): CircularDependencySummary {
    return CircularDependencySummaryFromJSONTyped(json, false);
}

export function CircularDependencySummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CircularDependencySummary {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCycles': json['totalCycles'],
        'filesInCycles': json['filesInCycles'],
        'highSeverityCount': json['highSeverityCount'],
        'mediumSeverityCount': json['mediumSeverityCount'],
        'lowSeverityCount': json['lowSeverityCount'],
    };
}

export function CircularDependencySummaryToJSON(value?: CircularDependencySummary | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'totalCycles': value['totalCycles'],
        'filesInCycles': value['filesInCycles'],
        'highSeverityCount': value['highSeverityCount'],
        'mediumSeverityCount': value['mediumSeverityCount'],
        'lowSeverityCount': value['lowSeverityCount'],
    };
}

