/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CycleEdge } from './CycleEdge';
import {
    CycleEdgeFromJSON,
    CycleEdgeFromJSONTyped,
    CycleEdgeToJSON,
} from './CycleEdge';

/**
 * A single dependency cycle (strongly connected component).
 * @export
 * @interface CircularDependencyCycle
 */
export interface CircularDependencyCycle {
    /**
     * Unique identifier for this cycle (e.g., cycle-1).
     * @type {string}
     * @memberof CircularDependencyCycle
     */
    id: string;
    /**
     * Files involved in this cycle, sorted alphabetically.
     * @type {Array<string>}
     * @memberof CircularDependencyCycle
     */
    files: Array<string>;
    /**
     * Import edges that form this cycle.
     * @type {Array<CycleEdge>}
     * @memberof CircularDependencyCycle
     */
    edges: Array<CycleEdge>;
    /**
     * Severity of this cycle based on cross-directory span and size.
     * @type {string}
     * @memberof CircularDependencyCycle
     */
    severity: CircularDependencyCycleSeverityEnum;
    /**
     * Suggested edge to break to resolve this cycle.
     * @type {string}
     * @memberof CircularDependencyCycle
     */
    breakingSuggestion?: string;
}


/**
 * @export
 */
export const CircularDependencyCycleSeverityEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high'
} as const;
export type CircularDependencyCycleSeverityEnum = typeof CircularDependencyCycleSeverityEnum[keyof typeof CircularDependencyCycleSeverityEnum];


/**
 * Check if a given object implements the CircularDependencyCycle interface.
 */
export function instanceOfCircularDependencyCycle(value: object): value is CircularDependencyCycle {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('files' in value) || value['files'] === undefined) return false;
    if (!('edges' in value) || value['edges'] === undefined) return false;
    if (!('severity' in value) || value['severity'] === undefined) return false;
    return true;
}

export function CircularDependencyCycleFromJSON(json: any): CircularDependencyCycle {
    return CircularDependencyCycleFromJSONTyped(json, false);
}

export function CircularDependencyCycleFromJSONTyped(json: any, ignoreDiscriminator: boolean): CircularDependencyCycle {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'files': json['files'],
        'edges': ((json['edges'] as Array<any>).map(CycleEdgeFromJSON)),
        'severity': json['severity'],
        'breakingSuggestion': json['breakingSuggestion'] == null ? undefined : json['breakingSuggestion'],
    };
}

export function CircularDependencyCycleToJSON(value?: CircularDependencyCycle | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'files': value['files'],
        'edges': ((value['edges'] as Array<any>).map(CycleEdgeToJSON)),
        'severity': value['severity'],
        'breakingSuggestion': value['breakingSuggestion'],
    };
}

