/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CircularDependencyMetadata } from './CircularDependencyMetadata';
import {
    CircularDependencyMetadataFromJSON,
    CircularDependencyMetadataFromJSONTyped,
    CircularDependencyMetadataToJSON,
} from './CircularDependencyMetadata';
import type { CircularDependencyCycle } from './CircularDependencyCycle';
import {
    CircularDependencyCycleFromJSON,
    CircularDependencyCycleFromJSONTyped,
    CircularDependencyCycleToJSON,
} from './CircularDependencyCycle';
import type { CircularDependencySummary } from './CircularDependencySummary';
import {
    CircularDependencySummaryFromJSON,
    CircularDependencySummaryFromJSONTyped,
    CircularDependencySummaryToJSON,
} from './CircularDependencySummary';

/**
 * Circular dependency analysis result containing detected cycles and summary.
 * @export
 * @interface CircularDependencyResponse
 */
export interface CircularDependencyResponse {
    /**
     * 
     * @type {CircularDependencyMetadata}
     * @memberof CircularDependencyResponse
     */
    metadata: CircularDependencyMetadata;
    /**
     * Detected dependency cycles.
     * @type {Array<CircularDependencyCycle>}
     * @memberof CircularDependencyResponse
     */
    cycles: Array<CircularDependencyCycle>;
    /**
     * 
     * @type {CircularDependencySummary}
     * @memberof CircularDependencyResponse
     */
    summary: CircularDependencySummary;
}

/**
 * Check if a given object implements the CircularDependencyResponse interface.
 */
export function instanceOfCircularDependencyResponse(value: object): value is CircularDependencyResponse {
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('cycles' in value) || value['cycles'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    return true;
}

export function CircularDependencyResponseFromJSON(json: any): CircularDependencyResponse {
    return CircularDependencyResponseFromJSONTyped(json, false);
}

export function CircularDependencyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CircularDependencyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': CircularDependencyMetadataFromJSON(json['metadata']),
        'cycles': ((json['cycles'] as Array<any>).map(CircularDependencyCycleFromJSON)),
        'summary': CircularDependencySummaryFromJSON(json['summary']),
    };
}

export function CircularDependencyResponseToJSON(value?: CircularDependencyResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'metadata': CircularDependencyMetadataToJSON(value['metadata']),
        'cycles': ((value['cycles'] as Array<any>).map(CircularDependencyCycleToJSON)),
        'summary': CircularDependencySummaryToJSON(value['summary']),
    };
}

