/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClassificationStats
 */
export interface ClassificationStats {
    /**
     * Total number of nodes in the graph
     * @type {number}
     * @memberof ClassificationStats
     */
    nodeCount: number;
    /**
     * Total number of relationships in the graph
     * @type {number}
     * @memberof ClassificationStats
     */
    relationshipCount: number;
    /**
     * Count of nodes by type
     * @type {{ [key: string]: number; }}
     * @memberof ClassificationStats
     */
    nodeTypes: { [key: string]: number; };
    /**
     * Count of relationships by type
     * @type {{ [key: string]: number; }}
     * @memberof ClassificationStats
     */
    relationshipTypes: { [key: string]: number; };
    /**
     * Number of domains discovered
     * @type {number}
     * @memberof ClassificationStats
     */
    domainCount: number;
    /**
     * Number of subdomains discovered
     * @type {number}
     * @memberof ClassificationStats
     */
    subdomainCount: number;
    /**
     * Number of files assigned to domains/subdomains
     * @type {number}
     * @memberof ClassificationStats
     */
    assignedFileCount: number;
    /**
     * Number of functions assigned to domains/subdomains
     * @type {number}
     * @memberof ClassificationStats
     */
    assignedFunctionCount: number;
    /**
     * Number of classes assigned to domains/subdomains
     * @type {number}
     * @memberof ClassificationStats
     */
    assignedClassCount: number;
    /**
     * Count of file assignments
     * @type {number}
     * @memberof ClassificationStats
     */
    fileAssignments: number;
    /**
     * Count of function assignments
     * @type {number}
     * @memberof ClassificationStats
     */
    functionAssignments: number;
    /**
     * Count of unassigned functions
     * @type {number}
     * @memberof ClassificationStats
     */
    unassignedFunctions: number;
    /**
     * Count of class assignments
     * @type {number}
     * @memberof ClassificationStats
     */
    classAssignments: number;
}

/**
 * Check if a given object implements the ClassificationStats interface.
 */
export function instanceOfClassificationStats(value: object): value is ClassificationStats {
    if (!('nodeCount' in value) || value['nodeCount'] === undefined) return false;
    if (!('relationshipCount' in value) || value['relationshipCount'] === undefined) return false;
    if (!('nodeTypes' in value) || value['nodeTypes'] === undefined) return false;
    if (!('relationshipTypes' in value) || value['relationshipTypes'] === undefined) return false;
    if (!('domainCount' in value) || value['domainCount'] === undefined) return false;
    if (!('subdomainCount' in value) || value['subdomainCount'] === undefined) return false;
    if (!('assignedFileCount' in value) || value['assignedFileCount'] === undefined) return false;
    if (!('assignedFunctionCount' in value) || value['assignedFunctionCount'] === undefined) return false;
    if (!('assignedClassCount' in value) || value['assignedClassCount'] === undefined) return false;
    if (!('fileAssignments' in value) || value['fileAssignments'] === undefined) return false;
    if (!('functionAssignments' in value) || value['functionAssignments'] === undefined) return false;
    if (!('unassignedFunctions' in value) || value['unassignedFunctions'] === undefined) return false;
    if (!('classAssignments' in value) || value['classAssignments'] === undefined) return false;
    return true;
}

export function ClassificationStatsFromJSON(json: any): ClassificationStats {
    return ClassificationStatsFromJSONTyped(json, false);
}

export function ClassificationStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassificationStats {
    if (json == null) {
        return json;
    }
    return {
        
        'nodeCount': json['nodeCount'],
        'relationshipCount': json['relationshipCount'],
        'nodeTypes': json['nodeTypes'],
        'relationshipTypes': json['relationshipTypes'],
        'domainCount': json['domainCount'],
        'subdomainCount': json['subdomainCount'],
        'assignedFileCount': json['assignedFileCount'],
        'assignedFunctionCount': json['assignedFunctionCount'],
        'assignedClassCount': json['assignedClassCount'],
        'fileAssignments': json['fileAssignments'],
        'functionAssignments': json['functionAssignments'],
        'unassignedFunctions': json['unassignedFunctions'],
        'classAssignments': json['classAssignments'],
    };
}

export function ClassificationStatsToJSON(value?: ClassificationStats | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'nodeCount': value['nodeCount'],
        'relationshipCount': value['relationshipCount'],
        'nodeTypes': value['nodeTypes'],
        'relationshipTypes': value['relationshipTypes'],
        'domainCount': value['domainCount'],
        'subdomainCount': value['subdomainCount'],
        'assignedFileCount': value['assignedFileCount'],
        'assignedFunctionCount': value['assignedFunctionCount'],
        'assignedClassCount': value['assignedClassCount'],
        'fileAssignments': value['fileAssignments'],
        'functionAssignments': value['functionAssignments'],
        'unassignedFunctions': value['unassignedFunctions'],
        'classAssignments': value['classAssignments'],
    };
}

