/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClassificationStats
 */
export interface ClassificationStats {
    /**
     * Number of domains discovered
     * @type {number}
     * @memberof ClassificationStats
     */
    domainCount: number;
    /**
     * Number of relationships
     * @type {number}
     * @memberof ClassificationStats
     */
    relationshipCount: number;
    /**
     * Count of file assignments
     * @type {number}
     * @memberof ClassificationStats
     */
    fileAssignments: number;
    /**
     * Count of function assignments
     * @type {number}
     * @memberof ClassificationStats
     */
    functionAssignments: number;
    /**
     * Count of unassigned functions
     * @type {number}
     * @memberof ClassificationStats
     */
    unassignedFunctions: number;
    /**
     * Count of class assignments
     * @type {number}
     * @memberof ClassificationStats
     */
    classAssignments: number;
}

/**
 * Check if a given object implements the ClassificationStats interface.
 */
export function instanceOfClassificationStats(value: object): value is ClassificationStats {
    if (!('domainCount' in value) || value['domainCount'] === undefined) return false;
    if (!('relationshipCount' in value) || value['relationshipCount'] === undefined) return false;
    if (!('fileAssignments' in value) || value['fileAssignments'] === undefined) return false;
    if (!('functionAssignments' in value) || value['functionAssignments'] === undefined) return false;
    if (!('unassignedFunctions' in value) || value['unassignedFunctions'] === undefined) return false;
    if (!('classAssignments' in value) || value['classAssignments'] === undefined) return false;
    return true;
}

export function ClassificationStatsFromJSON(json: any): ClassificationStats {
    return ClassificationStatsFromJSONTyped(json, false);
}

export function ClassificationStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassificationStats {
    if (json == null) {
        return json;
    }
    return {
        
        'domainCount': json['domainCount'],
        'relationshipCount': json['relationshipCount'],
        'fileAssignments': json['fileAssignments'],
        'functionAssignments': json['functionAssignments'],
        'unassignedFunctions': json['unassignedFunctions'],
        'classAssignments': json['classAssignments'],
    };
}

export function ClassificationStatsToJSON(value?: ClassificationStats | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'domainCount': value['domainCount'],
        'relationshipCount': value['relationshipCount'],
        'fileAssignments': value['fileAssignments'],
        'functionAssignments': value['functionAssignments'],
        'unassignedFunctions': value['unassignedFunctions'],
        'classAssignments': value['classAssignments'],
    };
}

