/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CodeGraphNode } from './CodeGraphNode';
import {
    CodeGraphNodeFromJSON,
    CodeGraphNodeFromJSONTyped,
    CodeGraphNodeToJSON,
} from './CodeGraphNode';
import type { CodeGraphRelationship } from './CodeGraphRelationship';
import {
    CodeGraphRelationshipFromJSON,
    CodeGraphRelationshipFromJSONTyped,
    CodeGraphRelationshipToJSON,
} from './CodeGraphRelationship';

/**
 * 
 * @export
 * @interface CodeGraphEnvelopeGraph
 */
export interface CodeGraphEnvelopeGraph {
    /**
     * 
     * @type {Array<CodeGraphNode>}
     * @memberof CodeGraphEnvelopeGraph
     */
    nodes: Array<CodeGraphNode>;
    /**
     * 
     * @type {Array<CodeGraphRelationship>}
     * @memberof CodeGraphEnvelopeGraph
     */
    relationships: Array<CodeGraphRelationship>;
}

/**
 * Check if a given object implements the CodeGraphEnvelopeGraph interface.
 */
export function instanceOfCodeGraphEnvelopeGraph(value: object): value is CodeGraphEnvelopeGraph {
    if (!('nodes' in value) || value['nodes'] === undefined) return false;
    if (!('relationships' in value) || value['relationships'] === undefined) return false;
    return true;
}

export function CodeGraphEnvelopeGraphFromJSON(json: any): CodeGraphEnvelopeGraph {
    return CodeGraphEnvelopeGraphFromJSONTyped(json, false);
}

export function CodeGraphEnvelopeGraphFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodeGraphEnvelopeGraph {
    if (json == null) {
        return json;
    }
    return {
        
        'nodes': ((json['nodes'] as Array<any>).map(CodeGraphNodeFromJSON)),
        'relationships': ((json['relationships'] as Array<any>).map(CodeGraphRelationshipFromJSON)),
    };
}

export function CodeGraphEnvelopeGraphToJSON(value?: CodeGraphEnvelopeGraph | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'nodes': ((value['nodes'] as Array<any>).map(CodeGraphNodeToJSON)),
        'relationships': ((value['relationships'] as Array<any>).map(CodeGraphRelationshipToJSON)),
    };
}

