/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CodeGraphEnvelope } from './CodeGraphEnvelope';
import {
    CodeGraphEnvelopeFromJSON,
    CodeGraphEnvelopeFromJSONTyped,
    CodeGraphEnvelopeToJSON,
} from './CodeGraphEnvelope';

/**
 * 
 * @export
 * @interface CodeGraphEnvelopeAsync
 */
export interface CodeGraphEnvelopeAsync {
    /**
     * Current status of the job.
     * @type {string}
     * @memberof CodeGraphEnvelopeAsync
     */
    status: CodeGraphEnvelopeAsyncStatusEnum;
    /**
     * Unique identifier for the job.
     * @type {string}
     * @memberof CodeGraphEnvelopeAsync
     */
    jobId: string;
    /**
     * Recommended seconds to wait before polling again.
     * @type {number}
     * @memberof CodeGraphEnvelopeAsync
     */
    retryAfter?: number;
    /**
     * Error message (present when status is failed).
     * @type {string}
     * @memberof CodeGraphEnvelopeAsync
     */
    error?: string;
    /**
     * 
     * @type {CodeGraphEnvelope}
     * @memberof CodeGraphEnvelopeAsync
     */
    result?: CodeGraphEnvelope;
}


/**
 * @export
 */
export const CodeGraphEnvelopeAsyncStatusEnum = {
    Pending: 'pending',
    Processing: 'processing',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type CodeGraphEnvelopeAsyncStatusEnum = typeof CodeGraphEnvelopeAsyncStatusEnum[keyof typeof CodeGraphEnvelopeAsyncStatusEnum];


/**
 * Check if a given object implements the CodeGraphEnvelopeAsync interface.
 */
export function instanceOfCodeGraphEnvelopeAsync(value: object): value is CodeGraphEnvelopeAsync {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    return true;
}

export function CodeGraphEnvelopeAsyncFromJSON(json: any): CodeGraphEnvelopeAsync {
    return CodeGraphEnvelopeAsyncFromJSONTyped(json, false);
}

export function CodeGraphEnvelopeAsyncFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodeGraphEnvelopeAsync {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'jobId': json['jobId'],
        'retryAfter': json['retryAfter'] == null ? undefined : json['retryAfter'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : CodeGraphEnvelopeFromJSON(json['result']),
    };
}

export function CodeGraphEnvelopeAsyncToJSON(value?: CodeGraphEnvelopeAsync | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'jobId': value['jobId'],
        'retryAfter': value['retryAfter'],
        'error': value['error'],
        'result': CodeGraphEnvelopeToJSON(value['result']),
    };
}

