/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CodeGraphNode
 */
export interface CodeGraphNode {
    /**
     * 
     * @type {string}
     * @memberof CodeGraphNode
     */
    id: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CodeGraphNode
     */
    labels?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CodeGraphNode
     */
    properties?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CodeGraphNode interface.
 */
export function instanceOfCodeGraphNode(value: object): value is CodeGraphNode {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CodeGraphNodeFromJSON(json: any): CodeGraphNode {
    return CodeGraphNodeFromJSONTyped(json, false);
}

export function CodeGraphNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodeGraphNode {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'labels': json['labels'] == null ? undefined : json['labels'],
        'properties': json['properties'] == null ? undefined : json['properties'],
    };
}

export function CodeGraphNodeToJSON(value?: CodeGraphNode | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'labels': value['labels'],
        'properties': value['properties'],
    };
}

