/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CodeGraphStats
 */
export interface CodeGraphStats {
    /**
     * 
     * @type {number}
     * @memberof CodeGraphStats
     */
    filesProcessed?: number;
    /**
     * 
     * @type {number}
     * @memberof CodeGraphStats
     */
    classes?: number;
    /**
     * 
     * @type {number}
     * @memberof CodeGraphStats
     */
    functions?: number;
    /**
     * 
     * @type {number}
     * @memberof CodeGraphStats
     */
    types?: number;
    /**
     * 
     * @type {number}
     * @memberof CodeGraphStats
     */
    processingTimeMs?: number;
}

/**
 * Check if a given object implements the CodeGraphStats interface.
 */
export function instanceOfCodeGraphStats(value: object): value is CodeGraphStats {
    return true;
}

export function CodeGraphStatsFromJSON(json: any): CodeGraphStats {
    return CodeGraphStatsFromJSONTyped(json, false);
}

export function CodeGraphStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodeGraphStats {
    if (json == null) {
        return json;
    }
    return {
        
        'filesProcessed': json['filesProcessed'] == null ? undefined : json['filesProcessed'],
        'classes': json['classes'] == null ? undefined : json['classes'],
        'functions': json['functions'] == null ? undefined : json['functions'],
        'types': json['types'] == null ? undefined : json['types'],
        'processingTimeMs': json['processingTimeMs'] == null ? undefined : json['processingTimeMs'],
    };
}

export function CodeGraphStatsToJSON(value?: CodeGraphStats | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'filesProcessed': value['filesProcessed'],
        'classes': value['classes'],
        'functions': value['functions'],
        'types': value['types'],
        'processingTimeMs': value['processingTimeMs'],
    };
}

