/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CodeGraphRelationship
 */
export interface CodeGraphRelationship {
    /**
     * 
     * @type {string}
     * @memberof CodeGraphRelationship
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CodeGraphRelationship
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof CodeGraphRelationship
     */
    startNode: string;
    /**
     * 
     * @type {string}
     * @memberof CodeGraphRelationship
     */
    endNode: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CodeGraphRelationship
     */
    properties?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CodeGraphRelationship interface.
 */
export function instanceOfCodeGraphRelationship(value: object): value is CodeGraphRelationship {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('startNode' in value) || value['startNode'] === undefined) return false;
    if (!('endNode' in value) || value['endNode'] === undefined) return false;
    return true;
}

export function CodeGraphRelationshipFromJSON(json: any): CodeGraphRelationship {
    return CodeGraphRelationshipFromJSONTyped(json, false);
}

export function CodeGraphRelationshipFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodeGraphRelationship {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'startNode': json['startNode'],
        'endNode': json['endNode'],
        'properties': json['properties'] == null ? undefined : json['properties'],
    };
}

export function CodeGraphRelationshipToJSON(value?: CodeGraphRelationship | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'type': value['type'],
        'startNode': value['startNode'],
        'endNode': value['endNode'],
        'properties': value['properties'],
    };
}

