/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Analysis metadata including timing and file information
 * @export
 * @interface CodeGraphEnvelopeMetadata
 */
export interface CodeGraphEnvelopeMetadata {
    /**
     * 
     * @type {Date}
     * @memberof CodeGraphEnvelopeMetadata
     */
    analysisStartTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CodeGraphEnvelopeMetadata
     */
    analysisEndTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof CodeGraphEnvelopeMetadata
     */
    fileCount?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof CodeGraphEnvelopeMetadata
     */
    languages?: Array<string>;
}

/**
 * Check if a given object implements the CodeGraphEnvelopeMetadata interface.
 */
export function instanceOfCodeGraphEnvelopeMetadata(value: object): value is CodeGraphEnvelopeMetadata {
    return true;
}

export function CodeGraphEnvelopeMetadataFromJSON(json: any): CodeGraphEnvelopeMetadata {
    return CodeGraphEnvelopeMetadataFromJSONTyped(json, false);
}

export function CodeGraphEnvelopeMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodeGraphEnvelopeMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'analysisStartTime': json['analysisStartTime'] == null ? undefined : (new Date(json['analysisStartTime'])),
        'analysisEndTime': json['analysisEndTime'] == null ? undefined : (new Date(json['analysisEndTime'])),
        'fileCount': json['fileCount'] == null ? undefined : json['fileCount'],
        'languages': json['languages'] == null ? undefined : json['languages'],
    };
}

export function CodeGraphEnvelopeMetadataToJSON(value?: CodeGraphEnvelopeMetadata | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'analysisStartTime': value['analysisStartTime'] == null ? undefined : ((value['analysisStartTime']).toISOString()),
        'analysisEndTime': value['analysisEndTime'] == null ? undefined : ((value['analysisEndTime']).toISOString()),
        'fileCount': value['fileCount'],
        'languages': value['languages'],
    };
}

