/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Test coverage breakdown for a domain.
 * @export
 * @interface CoverageByDomain
 */
export interface CoverageByDomain {
    /**
     * Domain name from domain classification.
     * @type {string}
     * @memberof CoverageByDomain
     */
    domain: string;
    /**
     * Total functions in the domain.
     * @type {number}
     * @memberof CoverageByDomain
     */
    totalFunctions: number;
    /**
     * Number of tested functions in the domain.
     * @type {number}
     * @memberof CoverageByDomain
     */
    testedFunctions: number;
    /**
     * Coverage percentage for the domain.
     * @type {number}
     * @memberof CoverageByDomain
     */
    coveragePercentage: number;
}

/**
 * Check if a given object implements the CoverageByDomain interface.
 */
export function instanceOfCoverageByDomain(value: object): value is CoverageByDomain {
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('totalFunctions' in value) || value['totalFunctions'] === undefined) return false;
    if (!('testedFunctions' in value) || value['testedFunctions'] === undefined) return false;
    if (!('coveragePercentage' in value) || value['coveragePercentage'] === undefined) return false;
    return true;
}

export function CoverageByDomainFromJSON(json: any): CoverageByDomain {
    return CoverageByDomainFromJSONTyped(json, false);
}

export function CoverageByDomainFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoverageByDomain {
    if (json == null) {
        return json;
    }
    return {
        
        'domain': json['domain'],
        'totalFunctions': json['totalFunctions'],
        'testedFunctions': json['testedFunctions'],
        'coveragePercentage': json['coveragePercentage'],
    };
}

export function CoverageByDomainToJSON(value?: CoverageByDomain | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'domain': value['domain'],
        'totalFunctions': value['totalFunctions'],
        'testedFunctions': value['testedFunctions'],
        'coveragePercentage': value['coveragePercentage'],
    };
}

