/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Test coverage breakdown for a production file.
 * @export
 * @interface CoverageByFile
 */
export interface CoverageByFile {
    /**
     * File path relative to repository root.
     * @type {string}
     * @memberof CoverageByFile
     */
    file: string;
    /**
     * Total functions in the file.
     * @type {number}
     * @memberof CoverageByFile
     */
    totalFunctions: number;
    /**
     * Number of tested functions in the file.
     * @type {number}
     * @memberof CoverageByFile
     */
    testedFunctions: number;
    /**
     * Number of untested functions in the file.
     * @type {number}
     * @memberof CoverageByFile
     */
    untestedFunctions: number;
    /**
     * Coverage percentage for the file.
     * @type {number}
     * @memberof CoverageByFile
     */
    coveragePercentage: number;
}

/**
 * Check if a given object implements the CoverageByFile interface.
 */
export function instanceOfCoverageByFile(value: object): value is CoverageByFile {
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('totalFunctions' in value) || value['totalFunctions'] === undefined) return false;
    if (!('testedFunctions' in value) || value['testedFunctions'] === undefined) return false;
    if (!('untestedFunctions' in value) || value['untestedFunctions'] === undefined) return false;
    if (!('coveragePercentage' in value) || value['coveragePercentage'] === undefined) return false;
    return true;
}

export function CoverageByFileFromJSON(json: any): CoverageByFile {
    return CoverageByFileFromJSONTyped(json, false);
}

export function CoverageByFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoverageByFile {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'],
        'totalFunctions': json['totalFunctions'],
        'testedFunctions': json['testedFunctions'],
        'untestedFunctions': json['untestedFunctions'],
        'coveragePercentage': json['coveragePercentage'],
    };
}

export function CoverageByFileToJSON(value?: CoverageByFile | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file': value['file'],
        'totalFunctions': value['totalFunctions'],
        'testedFunctions': value['testedFunctions'],
        'untestedFunctions': value['untestedFunctions'],
        'coveragePercentage': value['coveragePercentage'],
    };
}

