/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A file identified as critical due to high dependent count.
 * @export
 * @interface CriticalFile
 */
export interface CriticalFile {
    /**
     * File path relative to repository root.
     * @type {string}
     * @memberof CriticalFile
     */
    file: string;
    /**
     * Total number of transitive dependents.
     * @type {number}
     * @memberof CriticalFile
     */
    dependentCount: number;
    /**
     * Risk level based on dependent count.
     * @type {string}
     * @memberof CriticalFile
     */
    riskScore: CriticalFileRiskScoreEnum;
}


/**
 * @export
 */
export const CriticalFileRiskScoreEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Critical: 'critical'
} as const;
export type CriticalFileRiskScoreEnum = typeof CriticalFileRiskScoreEnum[keyof typeof CriticalFileRiskScoreEnum];


/**
 * Check if a given object implements the CriticalFile interface.
 */
export function instanceOfCriticalFile(value: object): value is CriticalFile {
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('dependentCount' in value) || value['dependentCount'] === undefined) return false;
    if (!('riskScore' in value) || value['riskScore'] === undefined) return false;
    return true;
}

export function CriticalFileFromJSON(json: any): CriticalFile {
    return CriticalFileFromJSONTyped(json, false);
}

export function CriticalFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): CriticalFile {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'],
        'dependentCount': json['dependentCount'],
        'riskScore': json['riskScore'],
    };
}

export function CriticalFileToJSON(value?: CriticalFile | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file': value['file'],
        'dependentCount': value['dependentCount'],
        'riskScore': value['riskScore'],
    };
}

