/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A dependency that crosses domain boundaries.
 * @export
 * @interface CrossDomainDependency
 */
export interface CrossDomainDependency {
    /**
     * Source domain.
     * @type {string}
     * @memberof CrossDomainDependency
     */
    from: string;
    /**
     * Target domain.
     * @type {string}
     * @memberof CrossDomainDependency
     */
    to: string;
    /**
     * Number of cross-domain edges.
     * @type {number}
     * @memberof CrossDomainDependency
     */
    edgeCount: number;
}

/**
 * Check if a given object implements the CrossDomainDependency interface.
 */
export function instanceOfCrossDomainDependency(value: object): value is CrossDomainDependency {
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('edgeCount' in value) || value['edgeCount'] === undefined) return false;
    return true;
}

export function CrossDomainDependencyFromJSON(json: any): CrossDomainDependency {
    return CrossDomainDependencyFromJSONTyped(json, false);
}

export function CrossDomainDependencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrossDomainDependency {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'],
        'to': json['to'],
        'edgeCount': json['edgeCount'],
    };
}

export function CrossDomainDependencyToJSON(value?: CrossDomainDependency | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'from': value['from'],
        'to': value['to'],
        'edgeCount': value['edgeCount'],
    };
}

