/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A directed import edge within a cycle.
 * @export
 * @interface CycleEdge
 */
export interface CycleEdge {
    /**
     * File path of the importing file.
     * @type {string}
     * @memberof CycleEdge
     */
    source: string;
    /**
     * File path of the imported file.
     * @type {string}
     * @memberof CycleEdge
     */
    target: string;
    /**
     * Symbols imported along this edge.
     * @type {Array<string>}
     * @memberof CycleEdge
     */
    importedSymbols: Array<string>;
}

/**
 * Check if a given object implements the CycleEdge interface.
 */
export function instanceOfCycleEdge(value: object): value is CycleEdge {
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('target' in value) || value['target'] === undefined) return false;
    if (!('importedSymbols' in value) || value['importedSymbols'] === undefined) return false;
    return true;
}

export function CycleEdgeFromJSON(json: any): CycleEdge {
    return CycleEdgeFromJSONTyped(json, false);
}

export function CycleEdgeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CycleEdge {
    if (json == null) {
        return json;
    }
    return {
        
        'source': json['source'],
        'target': json['target'],
        'importedSymbols': json['importedSymbols'],
    };
}

export function CycleEdgeToJSON(value?: CycleEdge | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'source': value['source'],
        'target': value['target'],
        'importedSymbols': value['importedSymbols'],
    };
}

