/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A code element identified as potentially dead (unreachable).
 * @export
 * @interface DeadCodeCandidate
 */
export interface DeadCodeCandidate {
    /**
     * File path relative to repository root.
     * @type {string}
     * @memberof DeadCodeCandidate
     */
    file: string;
    /**
     * Name of the function, class, or method.
     * @type {string}
     * @memberof DeadCodeCandidate
     */
    name: string;
    /**
     * Line number where the declaration starts.
     * @type {number}
     * @memberof DeadCodeCandidate
     */
    line: number;
    /**
     * Type of code element.
     * @type {string}
     * @memberof DeadCodeCandidate
     */
    type: DeadCodeCandidateTypeEnum;
    /**
     * Confidence level of dead code detection.
     * @type {string}
     * @memberof DeadCodeCandidate
     */
    confidence: DeadCodeCandidateConfidenceEnum;
    /**
     * Explanation of why this was flagged as dead code.
     * @type {string}
     * @memberof DeadCodeCandidate
     */
    reason: string;
}


/**
 * @export
 */
export const DeadCodeCandidateTypeEnum = {
    Function: 'function',
    Class: 'class',
    Method: 'method',
    Interface: 'interface',
    Type: 'type',
    Variable: 'variable',
    Constant: 'constant'
} as const;
export type DeadCodeCandidateTypeEnum = typeof DeadCodeCandidateTypeEnum[keyof typeof DeadCodeCandidateTypeEnum];

/**
 * @export
 */
export const DeadCodeCandidateConfidenceEnum = {
    High: 'high',
    Medium: 'medium',
    Low: 'low'
} as const;
export type DeadCodeCandidateConfidenceEnum = typeof DeadCodeCandidateConfidenceEnum[keyof typeof DeadCodeCandidateConfidenceEnum];


/**
 * Check if a given object implements the DeadCodeCandidate interface.
 */
export function instanceOfDeadCodeCandidate(value: object): value is DeadCodeCandidate {
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('line' in value) || value['line'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('confidence' in value) || value['confidence'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function DeadCodeCandidateFromJSON(json: any): DeadCodeCandidate {
    return DeadCodeCandidateFromJSONTyped(json, false);
}

export function DeadCodeCandidateFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeadCodeCandidate {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'],
        'name': json['name'],
        'line': json['line'],
        'type': json['type'],
        'confidence': json['confidence'],
        'reason': json['reason'],
    };
}

export function DeadCodeCandidateToJSON(value?: DeadCodeCandidate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file': value['file'],
        'name': value['name'],
        'line': value['line'],
        'type': value['type'],
        'confidence': value['confidence'],
        'reason': value['reason'],
    };
}

