/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeadCodeAnalysisMetadata } from './DeadCodeAnalysisMetadata';
import {
    DeadCodeAnalysisMetadataFromJSON,
    DeadCodeAnalysisMetadataFromJSONTyped,
    DeadCodeAnalysisMetadataToJSON,
} from './DeadCodeAnalysisMetadata';
import type { DeadCodeCandidate } from './DeadCodeCandidate';
import {
    DeadCodeCandidateFromJSON,
    DeadCodeCandidateFromJSONTyped,
    DeadCodeCandidateToJSON,
} from './DeadCodeCandidate';
import type { EntryPoint } from './EntryPoint';
import {
    EntryPointFromJSON,
    EntryPointFromJSONTyped,
    EntryPointToJSON,
} from './EntryPoint';
import type { AliveCodeItem } from './AliveCodeItem';
import {
    AliveCodeItemFromJSON,
    AliveCodeItemFromJSONTyped,
    AliveCodeItemToJSON,
} from './AliveCodeItem';

/**
 * Dead code analysis result containing candidates and alive code.
 * @export
 * @interface DeadCodeAnalysisResponse
 */
export interface DeadCodeAnalysisResponse {
    /**
     * 
     * @type {DeadCodeAnalysisMetadata}
     * @memberof DeadCodeAnalysisResponse
     */
    metadata: DeadCodeAnalysisMetadata;
    /**
     * Code elements with no detected callers or references.
     * @type {Array<DeadCodeCandidate>}
     * @memberof DeadCodeAnalysisResponse
     */
    deadCodeCandidates: Array<DeadCodeCandidate>;
    /**
     * Code elements with at least one caller or reference.
     * @type {Array<AliveCodeItem>}
     * @memberof DeadCodeAnalysisResponse
     */
    aliveCode: Array<AliveCodeItem>;
    /**
     * Detected entry points (exports, route handlers, main functions).
     * @type {Array<EntryPoint>}
     * @memberof DeadCodeAnalysisResponse
     */
    entryPoints: Array<EntryPoint>;
}

/**
 * Check if a given object implements the DeadCodeAnalysisResponse interface.
 */
export function instanceOfDeadCodeAnalysisResponse(value: object): value is DeadCodeAnalysisResponse {
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('deadCodeCandidates' in value) || value['deadCodeCandidates'] === undefined) return false;
    if (!('aliveCode' in value) || value['aliveCode'] === undefined) return false;
    if (!('entryPoints' in value) || value['entryPoints'] === undefined) return false;
    return true;
}

export function DeadCodeAnalysisResponseFromJSON(json: any): DeadCodeAnalysisResponse {
    return DeadCodeAnalysisResponseFromJSONTyped(json, false);
}

export function DeadCodeAnalysisResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeadCodeAnalysisResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': DeadCodeAnalysisMetadataFromJSON(json['metadata']),
        'deadCodeCandidates': ((json['deadCodeCandidates'] as Array<any>).map(DeadCodeCandidateFromJSON)),
        'aliveCode': ((json['aliveCode'] as Array<any>).map(AliveCodeItemFromJSON)),
        'entryPoints': ((json['entryPoints'] as Array<any>).map(EntryPointFromJSON)),
    };
}

export function DeadCodeAnalysisResponseToJSON(value?: DeadCodeAnalysisResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'metadata': DeadCodeAnalysisMetadataToJSON(value['metadata']),
        'deadCodeCandidates': ((value['deadCodeCandidates'] as Array<any>).map(DeadCodeCandidateToJSON)),
        'aliveCode': ((value['aliveCode'] as Array<any>).map(AliveCodeItemToJSON)),
        'entryPoints': ((value['entryPoints'] as Array<any>).map(EntryPointToJSON)),
    };
}

