/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Summary statistics for the dead code analysis.
 * @export
 * @interface DeadCodeAnalysisMetadata
 */
export interface DeadCodeAnalysisMetadata {
    /**
     * Total number of declarations (functions, classes, methods) analyzed.
     * @type {number}
     * @memberof DeadCodeAnalysisMetadata
     */
    totalDeclarations: number;
    /**
     * Number of dead code candidates found.
     * @type {number}
     * @memberof DeadCodeAnalysisMetadata
     */
    deadCodeCandidates: number;
    /**
     * Number of code elements with active references.
     * @type {number}
     * @memberof DeadCodeAnalysisMetadata
     */
    aliveCode: number;
    /**
     * Number of root files detected (files with no importers, used as entry points).
     * @type {number}
     * @memberof DeadCodeAnalysisMetadata
     */
    rootFilesCount?: number;
    /**
     * Number of functions detected as dead via transitive propagation (all callers are dead).
     * @type {number}
     * @memberof DeadCodeAnalysisMetadata
     */
    transitiveDeadCount?: number;
    /**
     * Number of exports detected as dead via symbol-level import analysis (exported but never imported by name).
     * @type {number}
     * @memberof DeadCodeAnalysisMetadata
     */
    symbolLevelDeadCount?: number;
    /**
     * Method used for analysis (e.g., 'dependency_graph_reachability').
     * @type {string}
     * @memberof DeadCodeAnalysisMetadata
     */
    analysisMethod: string;
    /**
     * Timestamp when analysis started.
     * @type {Date}
     * @memberof DeadCodeAnalysisMetadata
     */
    analysisStartTime?: Date;
    /**
     * Timestamp when analysis completed.
     * @type {Date}
     * @memberof DeadCodeAnalysisMetadata
     */
    analysisEndTime?: Date;
}

/**
 * Check if a given object implements the DeadCodeAnalysisMetadata interface.
 */
export function instanceOfDeadCodeAnalysisMetadata(value: object): value is DeadCodeAnalysisMetadata {
    if (!('totalDeclarations' in value) || value['totalDeclarations'] === undefined) return false;
    if (!('deadCodeCandidates' in value) || value['deadCodeCandidates'] === undefined) return false;
    if (!('aliveCode' in value) || value['aliveCode'] === undefined) return false;
    if (!('analysisMethod' in value) || value['analysisMethod'] === undefined) return false;
    return true;
}

export function DeadCodeAnalysisMetadataFromJSON(json: any): DeadCodeAnalysisMetadata {
    return DeadCodeAnalysisMetadataFromJSONTyped(json, false);
}

export function DeadCodeAnalysisMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeadCodeAnalysisMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'totalDeclarations': json['totalDeclarations'],
        'deadCodeCandidates': json['deadCodeCandidates'],
        'aliveCode': json['aliveCode'],
        'rootFilesCount': json['rootFilesCount'] == null ? undefined : json['rootFilesCount'],
        'transitiveDeadCount': json['transitiveDeadCount'] == null ? undefined : json['transitiveDeadCount'],
        'symbolLevelDeadCount': json['symbolLevelDeadCount'] == null ? undefined : json['symbolLevelDeadCount'],
        'analysisMethod': json['analysisMethod'],
        'analysisStartTime': json['analysisStartTime'] == null ? undefined : (new Date(json['analysisStartTime'])),
        'analysisEndTime': json['analysisEndTime'] == null ? undefined : (new Date(json['analysisEndTime'])),
    };
}

export function DeadCodeAnalysisMetadataToJSON(value?: DeadCodeAnalysisMetadata | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'totalDeclarations': value['totalDeclarations'],
        'deadCodeCandidates': value['deadCodeCandidates'],
        'aliveCode': value['aliveCode'],
        'rootFilesCount': value['rootFilesCount'],
        'transitiveDeadCount': value['transitiveDeadCount'],
        'symbolLevelDeadCount': value['symbolLevelDeadCount'],
        'analysisMethod': value['analysisMethod'],
        'analysisStartTime': value['analysisStartTime'] == null ? undefined : ((value['analysisStartTime']).toISOString()),
        'analysisEndTime': value['analysisEndTime'] == null ? undefined : ((value['analysisEndTime']).toISOString()),
    };
}

