/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeadCodeAnalysisResponse } from './DeadCodeAnalysisResponse';
import {
    DeadCodeAnalysisResponseFromJSON,
    DeadCodeAnalysisResponseFromJSONTyped,
    DeadCodeAnalysisResponseToJSON,
} from './DeadCodeAnalysisResponse';

/**
 * 
 * @export
 * @interface DeadCodeAnalysisResponseAsync
 */
export interface DeadCodeAnalysisResponseAsync {
    /**
     * Current status of the job.
     * @type {string}
     * @memberof DeadCodeAnalysisResponseAsync
     */
    status: DeadCodeAnalysisResponseAsyncStatusEnum;
    /**
     * Unique identifier for the job.
     * @type {string}
     * @memberof DeadCodeAnalysisResponseAsync
     */
    jobId: string;
    /**
     * Recommended seconds to wait before polling again.
     * @type {number}
     * @memberof DeadCodeAnalysisResponseAsync
     */
    retryAfter?: number;
    /**
     * Error message (present when status is failed).
     * @type {string}
     * @memberof DeadCodeAnalysisResponseAsync
     */
    error?: string;
    /**
     * 
     * @type {DeadCodeAnalysisResponse}
     * @memberof DeadCodeAnalysisResponseAsync
     */
    result?: DeadCodeAnalysisResponse;
}


/**
 * @export
 */
export const DeadCodeAnalysisResponseAsyncStatusEnum = {
    Pending: 'pending',
    Processing: 'processing',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type DeadCodeAnalysisResponseAsyncStatusEnum = typeof DeadCodeAnalysisResponseAsyncStatusEnum[keyof typeof DeadCodeAnalysisResponseAsyncStatusEnum];


/**
 * Check if a given object implements the DeadCodeAnalysisResponseAsync interface.
 */
export function instanceOfDeadCodeAnalysisResponseAsync(value: object): value is DeadCodeAnalysisResponseAsync {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    return true;
}

export function DeadCodeAnalysisResponseAsyncFromJSON(json: any): DeadCodeAnalysisResponseAsync {
    return DeadCodeAnalysisResponseAsyncFromJSONTyped(json, false);
}

export function DeadCodeAnalysisResponseAsyncFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeadCodeAnalysisResponseAsync {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'jobId': json['jobId'],
        'retryAfter': json['retryAfter'] == null ? undefined : json['retryAfter'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : DeadCodeAnalysisResponseFromJSON(json['result']),
    };
}

export function DeadCodeAnalysisResponseAsyncToJSON(value?: DeadCodeAnalysisResponseAsync | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'jobId': value['jobId'],
        'retryAfter': value['retryAfter'],
        'error': value['error'],
        'result': DeadCodeAnalysisResponseToJSON(value['result']),
    };
}

