/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainClassAssignment
 */
export interface DomainClassAssignment {
    /**
     * Class identifier
     * @type {string}
     * @memberof DomainClassAssignment
     */
    classId: string;
    /**
     * Assigned domain
     * @type {string}
     * @memberof DomainClassAssignment
     */
    domainName: string;
}

/**
 * Check if a given object implements the DomainClassAssignment interface.
 */
export function instanceOfDomainClassAssignment(value: object): value is DomainClassAssignment {
    if (!('classId' in value) || value['classId'] === undefined) return false;
    if (!('domainName' in value) || value['domainName'] === undefined) return false;
    return true;
}

export function DomainClassAssignmentFromJSON(json: any): DomainClassAssignment {
    return DomainClassAssignmentFromJSONTyped(json, false);
}

export function DomainClassAssignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainClassAssignment {
    if (json == null) {
        return json;
    }
    return {
        
        'classId': json['classId'],
        'domainName': json['domainName'],
    };
}

export function DomainClassAssignmentToJSON(value?: DomainClassAssignment | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'classId': value['classId'],
        'domainName': value['domainName'],
    };
}

