/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainClassificationResponse } from './DomainClassificationResponse';
import {
    DomainClassificationResponseFromJSON,
    DomainClassificationResponseFromJSONTyped,
    DomainClassificationResponseToJSON,
} from './DomainClassificationResponse';

/**
 * 
 * @export
 * @interface DomainClassificationResponseAsync
 */
export interface DomainClassificationResponseAsync {
    /**
     * Current status of the job.
     * @type {string}
     * @memberof DomainClassificationResponseAsync
     */
    status: DomainClassificationResponseAsyncStatusEnum;
    /**
     * Unique identifier for the job.
     * @type {string}
     * @memberof DomainClassificationResponseAsync
     */
    jobId: string;
    /**
     * Recommended seconds to wait before polling again.
     * @type {number}
     * @memberof DomainClassificationResponseAsync
     */
    retryAfter?: number;
    /**
     * Error message (present when status is failed).
     * @type {string}
     * @memberof DomainClassificationResponseAsync
     */
    error?: string;
    /**
     * 
     * @type {DomainClassificationResponse}
     * @memberof DomainClassificationResponseAsync
     */
    result?: DomainClassificationResponse;
}


/**
 * @export
 */
export const DomainClassificationResponseAsyncStatusEnum = {
    Pending: 'pending',
    Processing: 'processing',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type DomainClassificationResponseAsyncStatusEnum = typeof DomainClassificationResponseAsyncStatusEnum[keyof typeof DomainClassificationResponseAsyncStatusEnum];


/**
 * Check if a given object implements the DomainClassificationResponseAsync interface.
 */
export function instanceOfDomainClassificationResponseAsync(value: object): value is DomainClassificationResponseAsync {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    return true;
}

export function DomainClassificationResponseAsyncFromJSON(json: any): DomainClassificationResponseAsync {
    return DomainClassificationResponseAsyncFromJSONTyped(json, false);
}

export function DomainClassificationResponseAsyncFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainClassificationResponseAsync {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'jobId': json['jobId'],
        'retryAfter': json['retryAfter'] == null ? undefined : json['retryAfter'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : DomainClassificationResponseFromJSON(json['result']),
    };
}

export function DomainClassificationResponseAsyncToJSON(value?: DomainClassificationResponseAsync | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'jobId': value['jobId'],
        'retryAfter': value['retryAfter'],
        'error': value['error'],
        'result': DomainClassificationResponseToJSON(value['result']),
    };
}

