/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.4.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainRelationship
 */
export interface DomainRelationship {
    /**
     * Source domain or subdomain name/id
     * @type {string}
     * @memberof DomainRelationship
     */
    from: string;
    /**
     * Target domain or subdomain name/id
     * @type {string}
     * @memberof DomainRelationship
     */
    to: string;
    /**
     * Relationship type (e.g., aggregates, dependsOn, relatesTo)
     * @type {string}
     * @memberof DomainRelationship
     */
    type: string;
    /**
     * Numeric strength/weight (0-1 or small integer)
     * @type {number}
     * @memberof DomainRelationship
     */
    strength: number;
    /**
     * Optional explanation for the relationship
     * @type {string}
     * @memberof DomainRelationship
     */
    reason?: string;
}

/**
 * Check if a given object implements the DomainRelationship interface.
 */
export function instanceOfDomainRelationship(value: object): value is DomainRelationship {
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('strength' in value) || value['strength'] === undefined) return false;
    return true;
}

export function DomainRelationshipFromJSON(json: any): DomainRelationship {
    return DomainRelationshipFromJSONTyped(json, false);
}

export function DomainRelationshipFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainRelationship {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'],
        'to': json['to'],
        'type': json['type'],
        'strength': json['strength'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function DomainRelationshipToJSON(value?: DomainRelationship | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'from': value['from'],
        'to': value['to'],
        'type': value['type'],
        'strength': value['strength'],
        'reason': value['reason'],
    };
}

