/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainFileAssignment
 */
export interface DomainFileAssignment {
    /**
     * Repository-relative file path
     * @type {string}
     * @memberof DomainFileAssignment
     */
    filePath: string;
    /**
     * Assigned domain
     * @type {string}
     * @memberof DomainFileAssignment
     */
    domainName: string;
}

/**
 * Check if a given object implements the DomainFileAssignment interface.
 */
export function instanceOfDomainFileAssignment(value: object): value is DomainFileAssignment {
    if (!('filePath' in value) || value['filePath'] === undefined) return false;
    if (!('domainName' in value) || value['domainName'] === undefined) return false;
    return true;
}

export function DomainFileAssignmentFromJSON(json: any): DomainFileAssignment {
    return DomainFileAssignmentFromJSONTyped(json, false);
}

export function DomainFileAssignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainFileAssignment {
    if (json == null) {
        return json;
    }
    return {
        
        'filePath': json['filePath'],
        'domainName': json['domainName'],
    };
}

export function DomainFileAssignmentToJSON(value?: DomainFileAssignment | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'filePath': value['filePath'],
        'domainName': value['domainName'],
    };
}

