/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UnassignedFunction } from './UnassignedFunction';
import {
    UnassignedFunctionFromJSON,
    UnassignedFunctionFromJSONTyped,
    UnassignedFunctionToJSON,
} from './UnassignedFunction';
import type { DomainClassAssignment } from './DomainClassAssignment';
import {
    DomainClassAssignmentFromJSON,
    DomainClassAssignmentFromJSONTyped,
    DomainClassAssignmentToJSON,
} from './DomainClassAssignment';
import type { DomainFileAssignment } from './DomainFileAssignment';
import {
    DomainFileAssignmentFromJSON,
    DomainFileAssignmentFromJSONTyped,
    DomainFileAssignmentToJSON,
} from './DomainFileAssignment';
import type { DomainFunctionAssignment } from './DomainFunctionAssignment';
import {
    DomainFunctionAssignmentFromJSON,
    DomainFunctionAssignmentFromJSONTyped,
    DomainFunctionAssignmentToJSON,
} from './DomainFunctionAssignment';
import type { FunctionDescription } from './FunctionDescription';
import {
    FunctionDescriptionFromJSON,
    FunctionDescriptionFromJSONTyped,
    FunctionDescriptionToJSON,
} from './FunctionDescription';
import type { DomainRelationship } from './DomainRelationship';
import {
    DomainRelationshipFromJSON,
    DomainRelationshipFromJSONTyped,
    DomainRelationshipToJSON,
} from './DomainRelationship';
import type { DomainSummary } from './DomainSummary';
import {
    DomainSummaryFromJSON,
    DomainSummaryFromJSONTyped,
    DomainSummaryToJSON,
} from './DomainSummary';
import type { ClassificationStats } from './ClassificationStats';
import {
    ClassificationStatsFromJSON,
    ClassificationStatsFromJSONTyped,
    ClassificationStatsToJSON,
} from './ClassificationStats';
import type { DomainClassificationResponseGraph } from './DomainClassificationResponseGraph';
import {
    DomainClassificationResponseGraphFromJSON,
    DomainClassificationResponseGraphFromJSONTyped,
    DomainClassificationResponseGraphToJSON,
} from './DomainClassificationResponseGraph';
import type { CodeGraphEnvelopeMetadata } from './CodeGraphEnvelopeMetadata';
import {
    CodeGraphEnvelopeMetadataFromJSON,
    CodeGraphEnvelopeMetadataFromJSONTyped,
    CodeGraphEnvelopeMetadataToJSON,
} from './CodeGraphEnvelopeMetadata';

/**
 * 
 * @export
 * @interface DomainClassificationResponse
 */
export interface DomainClassificationResponse {
    /**
     * Unique identifier for this classification run
     * @type {string}
     * @memberof DomainClassificationResponse
     */
    runId: string;
    /**
     * 
     * @type {DomainClassificationResponseGraph}
     * @memberof DomainClassificationResponse
     */
    graph: DomainClassificationResponseGraph;
    /**
     * 
     * @type {CodeGraphEnvelopeMetadata}
     * @memberof DomainClassificationResponse
     */
    metadata: CodeGraphEnvelopeMetadata;
    /**
     * Array of primary domain entities
     * @type {Array<DomainSummary>}
     * @memberof DomainClassificationResponse
     */
    domains: Array<DomainSummary>;
    /**
     * High-level relationships between domains/subdomains
     * @type {Array<DomainRelationship>}
     * @memberof DomainClassificationResponse
     */
    relationships: Array<DomainRelationship>;
    /**
     * Mapping of files to domains
     * @type {Array<DomainFileAssignment>}
     * @memberof DomainClassificationResponse
     */
    fileAssignments: Array<DomainFileAssignment>;
    /**
     * Mapping of functions to subdomains
     * @type {Array<DomainFunctionAssignment>}
     * @memberof DomainClassificationResponse
     */
    functionAssignments: Array<DomainFunctionAssignment>;
    /**
     * Functions that could not be assigned to a domain/subdomain
     * @type {Array<UnassignedFunction>}
     * @memberof DomainClassificationResponse
     */
    unassignedFunctions: Array<UnassignedFunction>;
    /**
     * Mapping of classes to domains
     * @type {Array<DomainClassAssignment>}
     * @memberof DomainClassificationResponse
     */
    classAssignments: Array<DomainClassAssignment>;
    /**
     * Optional enriched descriptions per function
     * @type {Array<FunctionDescription>}
     * @memberof DomainClassificationResponse
     */
    functionDescriptions?: Array<FunctionDescription>;
    /**
     * 
     * @type {ClassificationStats}
     * @memberof DomainClassificationResponse
     */
    stats: ClassificationStats;
}

/**
 * Check if a given object implements the DomainClassificationResponse interface.
 */
export function instanceOfDomainClassificationResponse(value: object): value is DomainClassificationResponse {
    if (!('runId' in value) || value['runId'] === undefined) return false;
    if (!('graph' in value) || value['graph'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('domains' in value) || value['domains'] === undefined) return false;
    if (!('relationships' in value) || value['relationships'] === undefined) return false;
    if (!('fileAssignments' in value) || value['fileAssignments'] === undefined) return false;
    if (!('functionAssignments' in value) || value['functionAssignments'] === undefined) return false;
    if (!('unassignedFunctions' in value) || value['unassignedFunctions'] === undefined) return false;
    if (!('classAssignments' in value) || value['classAssignments'] === undefined) return false;
    if (!('stats' in value) || value['stats'] === undefined) return false;
    return true;
}

export function DomainClassificationResponseFromJSON(json: any): DomainClassificationResponse {
    return DomainClassificationResponseFromJSONTyped(json, false);
}

export function DomainClassificationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainClassificationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'runId': json['runId'],
        'graph': DomainClassificationResponseGraphFromJSON(json['graph']),
        'metadata': CodeGraphEnvelopeMetadataFromJSON(json['metadata']),
        'domains': ((json['domains'] as Array<any>).map(DomainSummaryFromJSON)),
        'relationships': ((json['relationships'] as Array<any>).map(DomainRelationshipFromJSON)),
        'fileAssignments': ((json['fileAssignments'] as Array<any>).map(DomainFileAssignmentFromJSON)),
        'functionAssignments': ((json['functionAssignments'] as Array<any>).map(DomainFunctionAssignmentFromJSON)),
        'unassignedFunctions': ((json['unassignedFunctions'] as Array<any>).map(UnassignedFunctionFromJSON)),
        'classAssignments': ((json['classAssignments'] as Array<any>).map(DomainClassAssignmentFromJSON)),
        'functionDescriptions': json['functionDescriptions'] == null ? undefined : ((json['functionDescriptions'] as Array<any>).map(FunctionDescriptionFromJSON)),
        'stats': ClassificationStatsFromJSON(json['stats']),
    };
}

export function DomainClassificationResponseToJSON(value?: DomainClassificationResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'runId': value['runId'],
        'graph': DomainClassificationResponseGraphToJSON(value['graph']),
        'metadata': CodeGraphEnvelopeMetadataToJSON(value['metadata']),
        'domains': ((value['domains'] as Array<any>).map(DomainSummaryToJSON)),
        'relationships': ((value['relationships'] as Array<any>).map(DomainRelationshipToJSON)),
        'fileAssignments': ((value['fileAssignments'] as Array<any>).map(DomainFileAssignmentToJSON)),
        'functionAssignments': ((value['functionAssignments'] as Array<any>).map(DomainFunctionAssignmentToJSON)),
        'unassignedFunctions': ((value['unassignedFunctions'] as Array<any>).map(UnassignedFunctionToJSON)),
        'classAssignments': ((value['classAssignments'] as Array<any>).map(DomainClassAssignmentToJSON)),
        'functionDescriptions': value['functionDescriptions'] == null ? undefined : ((value['functionDescriptions'] as Array<any>).map(FunctionDescriptionToJSON)),
        'stats': ClassificationStatsToJSON(value['stats']),
    };
}

