/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.4.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubdomainSummary } from './SubdomainSummary';
import {
    SubdomainSummaryFromJSON,
    SubdomainSummaryFromJSONTyped,
    SubdomainSummaryToJSON,
} from './SubdomainSummary';

/**
 * 
 * @export
 * @interface DomainSummary
 */
export interface DomainSummary {
    /**
     * Domain name (e.g., BillingAccount)
     * @type {string}
     * @memberof DomainSummary
     */
    name: string;
    /**
     * Human-readable description of the domain
     * @type {string}
     * @memberof DomainSummary
     */
    descriptionSummary: string;
    /**
     * Representative files backing the domain
     * @type {Array<string>}
     * @memberof DomainSummary
     */
    keyFiles: Array<string>;
    /**
     * Key responsibilities/concerns of the domain
     * @type {Array<string>}
     * @memberof DomainSummary
     */
    responsibilities: Array<string>;
    /**
     * Subdomains for this domain
     * @type {Array<SubdomainSummary>}
     * @memberof DomainSummary
     */
    subdomains: Array<SubdomainSummary>;
}

/**
 * Check if a given object implements the DomainSummary interface.
 */
export function instanceOfDomainSummary(value: object): value is DomainSummary {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('descriptionSummary' in value) || value['descriptionSummary'] === undefined) return false;
    if (!('keyFiles' in value) || value['keyFiles'] === undefined) return false;
    if (!('responsibilities' in value) || value['responsibilities'] === undefined) return false;
    if (!('subdomains' in value) || value['subdomains'] === undefined) return false;
    return true;
}

export function DomainSummaryFromJSON(json: any): DomainSummary {
    return DomainSummaryFromJSONTyped(json, false);
}

export function DomainSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'descriptionSummary': json['descriptionSummary'],
        'keyFiles': json['keyFiles'],
        'responsibilities': json['responsibilities'],
        'subdomains': ((json['subdomains'] as Array<any>).map(SubdomainSummaryFromJSON)),
    };
}

export function DomainSummaryToJSON(value?: DomainSummary | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'descriptionSummary': value['descriptionSummary'],
        'keyFiles': value['keyFiles'],
        'responsibilities': value['responsibilities'],
        'subdomains': ((value['subdomains'] as Array<any>).map(SubdomainSummaryToJSON)),
    };
}

