/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.4.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainFunctionAssignment
 */
export interface DomainFunctionAssignment {
    /**
     * Stable function identifier (matching codegraph/function models)
     * @type {string}
     * @memberof DomainFunctionAssignment
     */
    functionId: string;
    /**
     * Subdomain assigned to the function
     * @type {string}
     * @memberof DomainFunctionAssignment
     */
    subdomainName: string;
    /**
     * Optional parent domain containing the subdomain
     * @type {string}
     * @memberof DomainFunctionAssignment
     */
    parentDomain?: string;
}

/**
 * Check if a given object implements the DomainFunctionAssignment interface.
 */
export function instanceOfDomainFunctionAssignment(value: object): value is DomainFunctionAssignment {
    if (!('functionId' in value) || value['functionId'] === undefined) return false;
    if (!('subdomainName' in value) || value['subdomainName'] === undefined) return false;
    return true;
}

export function DomainFunctionAssignmentFromJSON(json: any): DomainFunctionAssignment {
    return DomainFunctionAssignmentFromJSONTyped(json, false);
}

export function DomainFunctionAssignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainFunctionAssignment {
    if (json == null) {
        return json;
    }
    return {
        
        'functionId': json['functionId'],
        'subdomainName': json['subdomainName'],
        'parentDomain': json['parentDomain'] == null ? undefined : json['parentDomain'],
    };
}

export function DomainFunctionAssignmentToJSON(value?: DomainFunctionAssignment | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'functionId': value['functionId'],
        'subdomainName': value['subdomainName'],
        'parentDomain': value['parentDomain'],
    };
}

