/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CodeGraphNode } from './CodeGraphNode';
import {
    CodeGraphNodeFromJSON,
    CodeGraphNodeFromJSONTyped,
    CodeGraphNodeToJSON,
} from './CodeGraphNode';
import type { CodeGraphRelationship } from './CodeGraphRelationship';
import {
    CodeGraphRelationshipFromJSON,
    CodeGraphRelationshipFromJSONTyped,
    CodeGraphRelationshipToJSON,
} from './CodeGraphRelationship';

/**
 * Graph representation with Domain and Subdomain nodes
 * @export
 * @interface DomainClassificationResponseGraph
 */
export interface DomainClassificationResponseGraph {
    /**
     * 
     * @type {Array<CodeGraphNode>}
     * @memberof DomainClassificationResponseGraph
     */
    nodes: Array<CodeGraphNode>;
    /**
     * 
     * @type {Array<CodeGraphRelationship>}
     * @memberof DomainClassificationResponseGraph
     */
    relationships: Array<CodeGraphRelationship>;
}

/**
 * Check if a given object implements the DomainClassificationResponseGraph interface.
 */
export function instanceOfDomainClassificationResponseGraph(value: object): value is DomainClassificationResponseGraph {
    if (!('nodes' in value) || value['nodes'] === undefined) return false;
    if (!('relationships' in value) || value['relationships'] === undefined) return false;
    return true;
}

export function DomainClassificationResponseGraphFromJSON(json: any): DomainClassificationResponseGraph {
    return DomainClassificationResponseGraphFromJSONTyped(json, false);
}

export function DomainClassificationResponseGraphFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainClassificationResponseGraph {
    if (json == null) {
        return json;
    }
    return {
        
        'nodes': ((json['nodes'] as Array<any>).map(CodeGraphNodeFromJSON)),
        'relationships': ((json['relationships'] as Array<any>).map(CodeGraphRelationshipFromJSON)),
    };
}

export function DomainClassificationResponseGraphToJSON(value?: DomainClassificationResponseGraph | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'nodes': ((value['nodes'] as Array<any>).map(CodeGraphNodeToJSON)),
        'relationships': ((value['relationships'] as Array<any>).map(CodeGraphRelationshipToJSON)),
    };
}

