/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A detected entry point that should not be flagged as dead code.
 * @export
 * @interface EntryPoint
 */
export interface EntryPoint {
    /**
     * File path relative to repository root.
     * @type {string}
     * @memberof EntryPoint
     */
    file: string;
    /**
     * Name of the entry point.
     * @type {string}
     * @memberof EntryPoint
     */
    name: string;
    /**
     * Line number where the entry point is declared.
     * @type {number}
     * @memberof EntryPoint
     */
    line: number;
    /**
     * Type of code element.
     * @type {string}
     * @memberof EntryPoint
     */
    type: EntryPointTypeEnum;
    /**
     * Reason this is considered an entry point (e.g., 'Module export', 'Route handler', 'Main function').
     * @type {string}
     * @memberof EntryPoint
     */
    reason: string;
}


/**
 * @export
 */
export const EntryPointTypeEnum = {
    Function: 'function',
    Class: 'class',
    Method: 'method',
    Interface: 'interface',
    Type: 'type',
    Variable: 'variable',
    Constant: 'constant'
} as const;
export type EntryPointTypeEnum = typeof EntryPointTypeEnum[keyof typeof EntryPointTypeEnum];


/**
 * Check if a given object implements the EntryPoint interface.
 */
export function instanceOfEntryPoint(value: object): value is EntryPoint {
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('line' in value) || value['line'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function EntryPointFromJSON(json: any): EntryPoint {
    return EntryPointFromJSONTyped(json, false);
}

export function EntryPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntryPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'],
        'name': json['name'],
        'line': json['line'],
        'type': json['type'],
        'reason': json['reason'],
    };
}

export function EntryPointToJSON(value?: EntryPoint | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file': value['file'],
        'name': value['name'],
        'line': value['line'],
        'type': value['type'],
        'reason': value['reason'],
    };
}

