/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorDetailsInner
 */
export interface ErrorDetailsInner {
    /**
     * Name of the field or parameter related to the error.
     * @type {string}
     * @memberof ErrorDetailsInner
     */
    field: string;
    /**
     * Description of the specific issue encountered.
     * @type {string}
     * @memberof ErrorDetailsInner
     */
    issue: string;
    /**
     * Where the field resides (e.g., query, path, body).
     * @type {string}
     * @memberof ErrorDetailsInner
     */
    location?: string;
}

/**
 * Check if a given object implements the ErrorDetailsInner interface.
 */
export function instanceOfErrorDetailsInner(value: object): value is ErrorDetailsInner {
    if (!('field' in value) || value['field'] === undefined) return false;
    if (!('issue' in value) || value['issue'] === undefined) return false;
    return true;
}

export function ErrorDetailsInnerFromJSON(json: any): ErrorDetailsInner {
    return ErrorDetailsInnerFromJSONTyped(json, false);
}

export function ErrorDetailsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorDetailsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'],
        'issue': json['issue'],
        'location': json['location'] == null ? undefined : json['location'],
    };
}

export function ErrorDetailsInnerToJSON(value?: ErrorDetailsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'field': value['field'],
        'issue': value['issue'],
        'location': value['location'],
    };
}

