/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FunctionDescription
 */
export interface FunctionDescription {
    /**
     * Function identifier
     * @type {string}
     * @memberof FunctionDescription
     */
    functionId: string;
    /**
     * Short summary of behavior
     * @type {string}
     * @memberof FunctionDescription
     */
    descriptionSummary: string;
    /**
     * Optional domain/subdomain association
     * @type {string}
     * @memberof FunctionDescription
     */
    domainName?: string;
}

/**
 * Check if a given object implements the FunctionDescription interface.
 */
export function instanceOfFunctionDescription(value: object): value is FunctionDescription {
    if (!('functionId' in value) || value['functionId'] === undefined) return false;
    if (!('descriptionSummary' in value) || value['descriptionSummary'] === undefined) return false;
    return true;
}

export function FunctionDescriptionFromJSON(json: any): FunctionDescription {
    return FunctionDescriptionFromJSONTyped(json, false);
}

export function FunctionDescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FunctionDescription {
    if (json == null) {
        return json;
    }
    return {
        
        'functionId': json['functionId'],
        'descriptionSummary': json['descriptionSummary'],
        'domainName': json['domainName'] == null ? undefined : json['domainName'],
    };
}

export function FunctionDescriptionToJSON(value?: FunctionDescription | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'functionId': value['functionId'],
        'descriptionSummary': value['descriptionSummary'],
        'domainName': value['domainName'],
    };
}

