/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Summary statistics for the impact analysis.
 * @export
 * @interface ImpactAnalysisMetadata
 */
export interface ImpactAnalysisMetadata {
    /**
     * Total number of files in the repository.
     * @type {number}
     * @memberof ImpactAnalysisMetadata
     */
    totalFiles: number;
    /**
     * Total number of functions analyzed.
     * @type {number}
     * @memberof ImpactAnalysisMetadata
     */
    totalFunctions: number;
    /**
     * Number of targets analyzed.
     * @type {number}
     * @memberof ImpactAnalysisMetadata
     */
    targetsAnalyzed: number;
    /**
     * Method used for impact analysis.
     * @type {string}
     * @memberof ImpactAnalysisMetadata
     */
    analysisMethod: string;
    /**
     * Timestamp when analysis started.
     * @type {Date}
     * @memberof ImpactAnalysisMetadata
     */
    analysisStartTime?: Date;
    /**
     * Timestamp when analysis completed.
     * @type {Date}
     * @memberof ImpactAnalysisMetadata
     */
    analysisEndTime?: Date;
}

/**
 * Check if a given object implements the ImpactAnalysisMetadata interface.
 */
export function instanceOfImpactAnalysisMetadata(value: object): value is ImpactAnalysisMetadata {
    if (!('totalFiles' in value) || value['totalFiles'] === undefined) return false;
    if (!('totalFunctions' in value) || value['totalFunctions'] === undefined) return false;
    if (!('targetsAnalyzed' in value) || value['targetsAnalyzed'] === undefined) return false;
    if (!('analysisMethod' in value) || value['analysisMethod'] === undefined) return false;
    return true;
}

export function ImpactAnalysisMetadataFromJSON(json: any): ImpactAnalysisMetadata {
    return ImpactAnalysisMetadataFromJSONTyped(json, false);
}

export function ImpactAnalysisMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImpactAnalysisMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'totalFiles': json['totalFiles'],
        'totalFunctions': json['totalFunctions'],
        'targetsAnalyzed': json['targetsAnalyzed'],
        'analysisMethod': json['analysisMethod'],
        'analysisStartTime': json['analysisStartTime'] == null ? undefined : (new Date(json['analysisStartTime'])),
        'analysisEndTime': json['analysisEndTime'] == null ? undefined : (new Date(json['analysisEndTime'])),
    };
}

export function ImpactAnalysisMetadataToJSON(value?: ImpactAnalysisMetadata | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'totalFiles': value['totalFiles'],
        'totalFunctions': value['totalFunctions'],
        'targetsAnalyzed': value['targetsAnalyzed'],
        'analysisMethod': value['analysisMethod'],
        'analysisStartTime': value['analysisStartTime'] == null ? undefined : ((value['analysisStartTime']).toISOString()),
        'analysisEndTime': value['analysisEndTime'] == null ? undefined : ((value['analysisEndTime']).toISOString()),
    };
}

