/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CrossDomainDependency } from './CrossDomainDependency';
import {
    CrossDomainDependencyFromJSON,
    CrossDomainDependencyFromJSONTyped,
    CrossDomainDependencyToJSON,
} from './CrossDomainDependency';
import type { CriticalFile } from './CriticalFile';
import {
    CriticalFileFromJSON,
    CriticalFileFromJSONTyped,
    CriticalFileToJSON,
} from './CriticalFile';

/**
 * Global metrics across all analyzed targets.
 * @export
 * @interface ImpactGlobalMetrics
 */
export interface ImpactGlobalMetrics {
    /**
     * Files with the highest dependent counts.
     * @type {Array<CriticalFile>}
     * @memberof ImpactGlobalMetrics
     */
    mostCriticalFiles?: Array<CriticalFile>;
    /**
     * Dependencies that cross domain boundaries (scaffolded, empty in v1).
     * @type {Array<CrossDomainDependency>}
     * @memberof ImpactGlobalMetrics
     */
    crossDomainDependencies?: Array<CrossDomainDependency>;
}

/**
 * Check if a given object implements the ImpactGlobalMetrics interface.
 */
export function instanceOfImpactGlobalMetrics(value: object): value is ImpactGlobalMetrics {
    return true;
}

export function ImpactGlobalMetricsFromJSON(json: any): ImpactGlobalMetrics {
    return ImpactGlobalMetricsFromJSONTyped(json, false);
}

export function ImpactGlobalMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImpactGlobalMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'mostCriticalFiles': json['mostCriticalFiles'] == null ? undefined : ((json['mostCriticalFiles'] as Array<any>).map(CriticalFileFromJSON)),
        'crossDomainDependencies': json['crossDomainDependencies'] == null ? undefined : ((json['crossDomainDependencies'] as Array<any>).map(CrossDomainDependencyFromJSON)),
    };
}

export function ImpactGlobalMetricsToJSON(value?: ImpactGlobalMetrics | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'mostCriticalFiles': value['mostCriticalFiles'] == null ? undefined : ((value['mostCriticalFiles'] as Array<any>).map(CriticalFileToJSON)),
        'crossDomainDependencies': value['crossDomainDependencies'] == null ? undefined : ((value['crossDomainDependencies'] as Array<any>).map(CrossDomainDependencyToJSON)),
    };
}

