/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AffectedFile } from './AffectedFile';
import {
    AffectedFileFromJSON,
    AffectedFileFromJSONTyped,
    AffectedFileToJSON,
} from './AffectedFile';
import type { AffectedFunction } from './AffectedFunction';
import {
    AffectedFunctionFromJSON,
    AffectedFunctionFromJSONTyped,
    AffectedFunctionToJSON,
} from './AffectedFunction';
import type { ImpactTarget } from './ImpactTarget';
import {
    ImpactTargetFromJSON,
    ImpactTargetFromJSONTyped,
    ImpactTargetToJSON,
} from './ImpactTarget';
import type { BlastRadius } from './BlastRadius';
import {
    BlastRadiusFromJSON,
    BlastRadiusFromJSONTyped,
    BlastRadiusToJSON,
} from './BlastRadius';
import type { AffectedEntryPoint } from './AffectedEntryPoint';
import {
    AffectedEntryPointFromJSON,
    AffectedEntryPointFromJSONTyped,
    AffectedEntryPointToJSON,
} from './AffectedEntryPoint';

/**
 * Impact analysis result for a single target.
 * @export
 * @interface ImpactResult
 */
export interface ImpactResult {
    /**
     * 
     * @type {ImpactTarget}
     * @memberof ImpactResult
     */
    target: ImpactTarget;
    /**
     * 
     * @type {BlastRadius}
     * @memberof ImpactResult
     */
    blastRadius: BlastRadius;
    /**
     * Functions affected by changes to this target.
     * @type {Array<AffectedFunction>}
     * @memberof ImpactResult
     */
    affectedFunctions: Array<AffectedFunction>;
    /**
     * Files affected by changes to this target.
     * @type {Array<AffectedFile>}
     * @memberof ImpactResult
     */
    affectedFiles: Array<AffectedFile>;
    /**
     * Entry points (route handlers, exports) affected by this target.
     * @type {Array<AffectedEntryPoint>}
     * @memberof ImpactResult
     */
    entryPointsAffected: Array<AffectedEntryPoint>;
}

/**
 * Check if a given object implements the ImpactResult interface.
 */
export function instanceOfImpactResult(value: object): value is ImpactResult {
    if (!('target' in value) || value['target'] === undefined) return false;
    if (!('blastRadius' in value) || value['blastRadius'] === undefined) return false;
    if (!('affectedFunctions' in value) || value['affectedFunctions'] === undefined) return false;
    if (!('affectedFiles' in value) || value['affectedFiles'] === undefined) return false;
    if (!('entryPointsAffected' in value) || value['entryPointsAffected'] === undefined) return false;
    return true;
}

export function ImpactResultFromJSON(json: any): ImpactResult {
    return ImpactResultFromJSONTyped(json, false);
}

export function ImpactResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImpactResult {
    if (json == null) {
        return json;
    }
    return {
        
        'target': ImpactTargetFromJSON(json['target']),
        'blastRadius': BlastRadiusFromJSON(json['blastRadius']),
        'affectedFunctions': ((json['affectedFunctions'] as Array<any>).map(AffectedFunctionFromJSON)),
        'affectedFiles': ((json['affectedFiles'] as Array<any>).map(AffectedFileFromJSON)),
        'entryPointsAffected': ((json['entryPointsAffected'] as Array<any>).map(AffectedEntryPointFromJSON)),
    };
}

export function ImpactResultToJSON(value?: ImpactResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'target': ImpactTargetToJSON(value['target']),
        'blastRadius': BlastRadiusToJSON(value['blastRadius']),
        'affectedFunctions': ((value['affectedFunctions'] as Array<any>).map(AffectedFunctionToJSON)),
        'affectedFiles': ((value['affectedFiles'] as Array<any>).map(AffectedFileToJSON)),
        'entryPointsAffected': ((value['entryPointsAffected'] as Array<any>).map(AffectedEntryPointToJSON)),
    };
}

