/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImpactResult } from './ImpactResult';
import {
    ImpactResultFromJSON,
    ImpactResultFromJSONTyped,
    ImpactResultToJSON,
} from './ImpactResult';
import type { ImpactGlobalMetrics } from './ImpactGlobalMetrics';
import {
    ImpactGlobalMetricsFromJSON,
    ImpactGlobalMetricsFromJSONTyped,
    ImpactGlobalMetricsToJSON,
} from './ImpactGlobalMetrics';
import type { ImpactAnalysisMetadata } from './ImpactAnalysisMetadata';
import {
    ImpactAnalysisMetadataFromJSON,
    ImpactAnalysisMetadataFromJSONTyped,
    ImpactAnalysisMetadataToJSON,
} from './ImpactAnalysisMetadata';

/**
 * Impact analysis result containing blast radius and affected functions/files.
 * @export
 * @interface ImpactAnalysisResponse
 */
export interface ImpactAnalysisResponse {
    /**
     * 
     * @type {ImpactAnalysisMetadata}
     * @memberof ImpactAnalysisResponse
     */
    metadata: ImpactAnalysisMetadata;
    /**
     * Impact results for each analyzed target.
     * @type {Array<ImpactResult>}
     * @memberof ImpactAnalysisResponse
     */
    impacts: Array<ImpactResult>;
    /**
     * 
     * @type {ImpactGlobalMetrics}
     * @memberof ImpactAnalysisResponse
     */
    globalMetrics: ImpactGlobalMetrics;
}

/**
 * Check if a given object implements the ImpactAnalysisResponse interface.
 */
export function instanceOfImpactAnalysisResponse(value: object): value is ImpactAnalysisResponse {
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('impacts' in value) || value['impacts'] === undefined) return false;
    if (!('globalMetrics' in value) || value['globalMetrics'] === undefined) return false;
    return true;
}

export function ImpactAnalysisResponseFromJSON(json: any): ImpactAnalysisResponse {
    return ImpactAnalysisResponseFromJSONTyped(json, false);
}

export function ImpactAnalysisResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImpactAnalysisResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': ImpactAnalysisMetadataFromJSON(json['metadata']),
        'impacts': ((json['impacts'] as Array<any>).map(ImpactResultFromJSON)),
        'globalMetrics': ImpactGlobalMetricsFromJSON(json['globalMetrics']),
    };
}

export function ImpactAnalysisResponseToJSON(value?: ImpactAnalysisResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'metadata': ImpactAnalysisMetadataToJSON(value['metadata']),
        'impacts': ((value['impacts'] as Array<any>).map(ImpactResultToJSON)),
        'globalMetrics': ImpactGlobalMetricsToJSON(value['globalMetrics']),
    };
}

