/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImpactAnalysisResponse } from './ImpactAnalysisResponse';
import {
    ImpactAnalysisResponseFromJSON,
    ImpactAnalysisResponseFromJSONTyped,
    ImpactAnalysisResponseToJSON,
} from './ImpactAnalysisResponse';

/**
 * 
 * @export
 * @interface ImpactAnalysisResponseAsync
 */
export interface ImpactAnalysisResponseAsync {
    /**
     * Current status of the job.
     * @type {string}
     * @memberof ImpactAnalysisResponseAsync
     */
    status: ImpactAnalysisResponseAsyncStatusEnum;
    /**
     * Unique identifier for the job.
     * @type {string}
     * @memberof ImpactAnalysisResponseAsync
     */
    jobId: string;
    /**
     * Recommended seconds to wait before polling again.
     * @type {number}
     * @memberof ImpactAnalysisResponseAsync
     */
    retryAfter?: number;
    /**
     * Error message (present when status is failed).
     * @type {string}
     * @memberof ImpactAnalysisResponseAsync
     */
    error?: string;
    /**
     * 
     * @type {ImpactAnalysisResponse}
     * @memberof ImpactAnalysisResponseAsync
     */
    result?: ImpactAnalysisResponse;
}


/**
 * @export
 */
export const ImpactAnalysisResponseAsyncStatusEnum = {
    Pending: 'pending',
    Processing: 'processing',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type ImpactAnalysisResponseAsyncStatusEnum = typeof ImpactAnalysisResponseAsyncStatusEnum[keyof typeof ImpactAnalysisResponseAsyncStatusEnum];


/**
 * Check if a given object implements the ImpactAnalysisResponseAsync interface.
 */
export function instanceOfImpactAnalysisResponseAsync(value: object): value is ImpactAnalysisResponseAsync {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    return true;
}

export function ImpactAnalysisResponseAsyncFromJSON(json: any): ImpactAnalysisResponseAsync {
    return ImpactAnalysisResponseAsyncFromJSONTyped(json, false);
}

export function ImpactAnalysisResponseAsyncFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImpactAnalysisResponseAsync {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'jobId': json['jobId'],
        'retryAfter': json['retryAfter'] == null ? undefined : json['retryAfter'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : ImpactAnalysisResponseFromJSON(json['result']),
    };
}

export function ImpactAnalysisResponseAsyncToJSON(value?: ImpactAnalysisResponseAsync | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'jobId': value['jobId'],
        'retryAfter': value['retryAfter'],
        'error': value['error'],
        'result': ImpactAnalysisResponseToJSON(value['result']),
    };
}

