/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The target file or function being analyzed for impact.
 * @export
 * @interface ImpactTarget
 */
export interface ImpactTarget {
    /**
     * File path relative to repository root.
     * @type {string}
     * @memberof ImpactTarget
     */
    file: string;
    /**
     * Function or method name (if targeting a specific function).
     * @type {string}
     * @memberof ImpactTarget
     */
    name?: string;
    /**
     * Line number of the target declaration.
     * @type {number}
     * @memberof ImpactTarget
     */
    line?: number;
    /**
     * Type of the target element.
     * @type {string}
     * @memberof ImpactTarget
     */
    type: ImpactTargetTypeEnum;
}


/**
 * @export
 */
export const ImpactTargetTypeEnum = {
    File: 'file',
    Function: 'function',
    Method: 'method',
    Class: 'class'
} as const;
export type ImpactTargetTypeEnum = typeof ImpactTargetTypeEnum[keyof typeof ImpactTargetTypeEnum];


/**
 * Check if a given object implements the ImpactTarget interface.
 */
export function instanceOfImpactTarget(value: object): value is ImpactTarget {
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ImpactTargetFromJSON(json: any): ImpactTarget {
    return ImpactTargetFromJSONTyped(json, false);
}

export function ImpactTargetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImpactTarget {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'],
        'name': json['name'] == null ? undefined : json['name'],
        'line': json['line'] == null ? undefined : json['line'],
        'type': json['type'],
    };
}

export function ImpactTargetToJSON(value?: ImpactTarget | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file': value['file'],
        'name': value['name'],
        'line': value['line'],
        'type': value['type'],
    };
}

