/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Common fields for async job status tracking.
 * @export
 * @interface JobStatus
 */
export interface JobStatus {
    /**
     * Current status of the job.
     * @type {string}
     * @memberof JobStatus
     */
    status: JobStatusStatusEnum;
    /**
     * Unique identifier for the job.
     * @type {string}
     * @memberof JobStatus
     */
    jobId: string;
    /**
     * Recommended seconds to wait before polling again.
     * @type {number}
     * @memberof JobStatus
     */
    retryAfter?: number;
    /**
     * Error message (present when status is failed).
     * @type {string}
     * @memberof JobStatus
     */
    error?: string;
}


/**
 * @export
 */
export const JobStatusStatusEnum = {
    Pending: 'pending',
    Processing: 'processing',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type JobStatusStatusEnum = typeof JobStatusStatusEnum[keyof typeof JobStatusStatusEnum];


/**
 * Check if a given object implements the JobStatus interface.
 */
export function instanceOfJobStatus(value: object): value is JobStatus {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    return true;
}

export function JobStatusFromJSON(json: any): JobStatus {
    return JobStatusFromJSONTyped(json, false);
}

export function JobStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'jobId': json['jobId'],
        'retryAfter': json['retryAfter'] == null ? undefined : json['retryAfter'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function JobStatusToJSON(value?: JobStatus | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'jobId': value['jobId'],
        'retryAfter': value['retryAfter'],
        'error': value['error'],
    };
}

