/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.6.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorDetailsInner } from './ErrorDetailsInner';
import {
    ErrorDetailsInnerFromJSON,
    ErrorDetailsInnerFromJSONTyped,
    ErrorDetailsInnerToJSON,
} from './ErrorDetailsInner';

/**
 * Standardized error payload returned by the API.
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * HTTP status code associated with the error.
     * @type {number}
     * @memberof ModelError
     */
    status: number;
    /**
     * Stable, machine-readable error identifier.
     * @type {string}
     * @memberof ModelError
     */
    code: string;
    /**
     * Human-readable description of the error.
     * @type {string}
     * @memberof ModelError
     */
    message: string;
    /**
     * ISO-8601 timestamp indicating when the error occurred.
     * @type {Date}
     * @memberof ModelError
     */
    timestamp: Date;
    /**
     * Correlation identifier for tracing the failing request.
     * @type {string}
     * @memberof ModelError
     */
    requestId?: string;
    /**
     * Optional list of contextual error details.
     * @type {Array<ErrorDetailsInner>}
     * @memberof ModelError
     */
    details?: Array<ErrorDetailsInner>;
}

/**
 * Check if a given object implements the ModelError interface.
 */
export function instanceOfModelError(value: object): value is ModelError {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function ModelErrorFromJSON(json: any): ModelError {
    return ModelErrorFromJSONTyped(json, false);
}

export function ModelErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelError {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'code': json['code'],
        'message': json['message'],
        'timestamp': (new Date(json['timestamp'])),
        'requestId': json['requestId'] == null ? undefined : json['requestId'],
        'details': json['details'] == null ? undefined : ((json['details'] as Array<any>).map(ErrorDetailsInnerFromJSON)),
    };
}

export function ModelErrorToJSON(value?: ModelError | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'code': value['code'],
        'message': value['message'],
        'timestamp': ((value['timestamp']).toISOString()),
        'requestId': value['requestId'],
        'details': value['details'] == null ? undefined : ((value['details'] as Array<any>).map(ErrorDetailsInnerToJSON)),
    };
}

