/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The nearest function in the call graph that has test coverage.
 * @export
 * @interface NearestTestedCaller
 */
export interface NearestTestedCaller {
    /**
     * File path of the nearest tested function.
     * @type {string}
     * @memberof NearestTestedCaller
     */
    file: string;
    /**
     * Name of the nearest tested function.
     * @type {string}
     * @memberof NearestTestedCaller
     */
    name: string;
    /**
     * Number of call graph hops to the nearest tested function.
     * @type {number}
     * @memberof NearestTestedCaller
     */
    distance: number;
}

/**
 * Check if a given object implements the NearestTestedCaller interface.
 */
export function instanceOfNearestTestedCaller(value: object): value is NearestTestedCaller {
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('distance' in value) || value['distance'] === undefined) return false;
    return true;
}

export function NearestTestedCallerFromJSON(json: any): NearestTestedCaller {
    return NearestTestedCallerFromJSONTyped(json, false);
}

export function NearestTestedCallerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NearestTestedCaller {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'],
        'name': json['name'],
        'distance': json['distance'],
    };
}

export function NearestTestedCallerToJSON(value?: NearestTestedCaller | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file': value['file'],
        'name': value['name'],
        'distance': value['distance'],
    };
}

