/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubdomainSummary
 */
export interface SubdomainSummary {
    /**
     * Subdomain name
     * @type {string}
     * @memberof SubdomainSummary
     */
    name: string;
    /**
     * Concise description of the subdomain
     * @type {string}
     * @memberof SubdomainSummary
     */
    descriptionSummary: string;
    /**
     * List of file paths assigned to this subdomain
     * @type {Array<string>}
     * @memberof SubdomainSummary
     */
    files: Array<string>;
    /**
     * List of function IDs assigned to this subdomain
     * @type {Array<string>}
     * @memberof SubdomainSummary
     */
    functions: Array<string>;
    /**
     * List of class IDs assigned to this subdomain
     * @type {Array<string>}
     * @memberof SubdomainSummary
     */
    classes: Array<string>;
}

/**
 * Check if a given object implements the SubdomainSummary interface.
 */
export function instanceOfSubdomainSummary(value: object): value is SubdomainSummary {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('descriptionSummary' in value) || value['descriptionSummary'] === undefined) return false;
    if (!('files' in value) || value['files'] === undefined) return false;
    if (!('functions' in value) || value['functions'] === undefined) return false;
    if (!('classes' in value) || value['classes'] === undefined) return false;
    return true;
}

export function SubdomainSummaryFromJSON(json: any): SubdomainSummary {
    return SubdomainSummaryFromJSONTyped(json, false);
}

export function SubdomainSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubdomainSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'descriptionSummary': json['descriptionSummary'],
        'files': json['files'],
        'functions': json['functions'],
        'classes': json['classes'],
    };
}

export function SubdomainSummaryToJSON(value?: SubdomainSummary | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'descriptionSummary': value['descriptionSummary'],
        'files': value['files'],
        'functions': value['functions'],
        'classes': value['classes'],
    };
}

