/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Graph statistics including node and relationship counts by type
 * @export
 * @interface SupermodelIRStats
 */
export interface SupermodelIRStats {
    /**
     * 
     * @type {number}
     * @memberof SupermodelIRStats
     */
    nodeCount?: number;
    /**
     * 
     * @type {number}
     * @memberof SupermodelIRStats
     */
    relationshipCount?: number;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof SupermodelIRStats
     */
    nodeTypes?: { [key: string]: number; };
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof SupermodelIRStats
     */
    relationshipTypes?: { [key: string]: number; };
}

/**
 * Check if a given object implements the SupermodelIRStats interface.
 */
export function instanceOfSupermodelIRStats(value: object): value is SupermodelIRStats {
    return true;
}

export function SupermodelIRStatsFromJSON(json: any): SupermodelIRStats {
    return SupermodelIRStatsFromJSONTyped(json, false);
}

export function SupermodelIRStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupermodelIRStats {
    if (json == null) {
        return json;
    }
    return {
        
        'nodeCount': json['nodeCount'] == null ? undefined : json['nodeCount'],
        'relationshipCount': json['relationshipCount'] == null ? undefined : json['relationshipCount'],
        'nodeTypes': json['nodeTypes'] == null ? undefined : json['nodeTypes'],
        'relationshipTypes': json['relationshipTypes'] == null ? undefined : json['relationshipTypes'],
    };
}

export function SupermodelIRStatsToJSON(value?: SupermodelIRStats | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'nodeCount': value['nodeCount'],
        'relationshipCount': value['relationshipCount'],
        'nodeTypes': value['nodeTypes'],
        'relationshipTypes': value['relationshipTypes'],
    };
}

