/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.4.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SupermodelArtifact
 */
export interface SupermodelArtifact {
    /**
     * Unique identifier for the artifact.
     * @type {string}
     * @memberof SupermodelArtifact
     */
    id: string;
    /**
     * Artifact kind such as graph, summary, or embedding.
     * @type {string}
     * @memberof SupermodelArtifact
     */
    kind: string;
    /**
     * Human-readable name for the artifact.
     * @type {string}
     * @memberof SupermodelArtifact
     */
    label: string;
    /**
     * Additional metadata for consuming the artifact.
     * @type {{ [key: string]: any; }}
     * @memberof SupermodelArtifact
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the SupermodelArtifact interface.
 */
export function instanceOfSupermodelArtifact(value: object): value is SupermodelArtifact {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function SupermodelArtifactFromJSON(json: any): SupermodelArtifact {
    return SupermodelArtifactFromJSONTyped(json, false);
}

export function SupermodelArtifactFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupermodelArtifact {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'kind': json['kind'],
        'label': json['label'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function SupermodelArtifactToJSON(value?: SupermodelArtifact | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'kind': value['kind'],
        'label': value['label'],
        'metadata': value['metadata'],
    };
}

