/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SupermodelIR } from './SupermodelIR';
import {
    SupermodelIRFromJSON,
    SupermodelIRFromJSONTyped,
    SupermodelIRToJSON,
} from './SupermodelIR';

/**
 * 
 * @export
 * @interface SupermodelIRAsync
 */
export interface SupermodelIRAsync {
    /**
     * Current status of the job.
     * @type {string}
     * @memberof SupermodelIRAsync
     */
    status: SupermodelIRAsyncStatusEnum;
    /**
     * Unique identifier for the job.
     * @type {string}
     * @memberof SupermodelIRAsync
     */
    jobId: string;
    /**
     * Recommended seconds to wait before polling again.
     * @type {number}
     * @memberof SupermodelIRAsync
     */
    retryAfter?: number;
    /**
     * Error message (present when status is failed).
     * @type {string}
     * @memberof SupermodelIRAsync
     */
    error?: string;
    /**
     * 
     * @type {SupermodelIR}
     * @memberof SupermodelIRAsync
     */
    result?: SupermodelIR;
}


/**
 * @export
 */
export const SupermodelIRAsyncStatusEnum = {
    Pending: 'pending',
    Processing: 'processing',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type SupermodelIRAsyncStatusEnum = typeof SupermodelIRAsyncStatusEnum[keyof typeof SupermodelIRAsyncStatusEnum];


/**
 * Check if a given object implements the SupermodelIRAsync interface.
 */
export function instanceOfSupermodelIRAsync(value: object): value is SupermodelIRAsync {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    return true;
}

export function SupermodelIRAsyncFromJSON(json: any): SupermodelIRAsync {
    return SupermodelIRAsyncFromJSONTyped(json, false);
}

export function SupermodelIRAsyncFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupermodelIRAsync {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'jobId': json['jobId'],
        'retryAfter': json['retryAfter'] == null ? undefined : json['retryAfter'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : SupermodelIRFromJSON(json['result']),
    };
}

export function SupermodelIRAsyncToJSON(value?: SupermodelIRAsync | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'jobId': value['jobId'],
        'retryAfter': value['retryAfter'],
        'error': value['error'],
        'result': SupermodelIRToJSON(value['result']),
    };
}

