/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CodeGraphNode } from './CodeGraphNode';
import {
    CodeGraphNodeFromJSON,
    CodeGraphNodeFromJSONTyped,
    CodeGraphNodeToJSON,
} from './CodeGraphNode';
import type { CodeGraphRelationship } from './CodeGraphRelationship';
import {
    CodeGraphRelationshipFromJSON,
    CodeGraphRelationshipFromJSONTyped,
    CodeGraphRelationshipToJSON,
} from './CodeGraphRelationship';

/**
 * Unified code graph containing all nodes and relationships.
 * @export
 * @interface SupermodelIRGraph
 */
export interface SupermodelIRGraph {
    /**
     * All nodes from parse graph, call graph, and domain classification.
     * @type {Array<CodeGraphNode>}
     * @memberof SupermodelIRGraph
     */
    nodes: Array<CodeGraphNode>;
    /**
     * All relationships including contains, imports, calls, and belongsTo.
     * @type {Array<CodeGraphRelationship>}
     * @memberof SupermodelIRGraph
     */
    relationships: Array<CodeGraphRelationship>;
}

/**
 * Check if a given object implements the SupermodelIRGraph interface.
 */
export function instanceOfSupermodelIRGraph(value: object): value is SupermodelIRGraph {
    if (!('nodes' in value) || value['nodes'] === undefined) return false;
    if (!('relationships' in value) || value['relationships'] === undefined) return false;
    return true;
}

export function SupermodelIRGraphFromJSON(json: any): SupermodelIRGraph {
    return SupermodelIRGraphFromJSONTyped(json, false);
}

export function SupermodelIRGraphFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupermodelIRGraph {
    if (json == null) {
        return json;
    }
    return {
        
        'nodes': ((json['nodes'] as Array<any>).map(CodeGraphNodeFromJSON)),
        'relationships': ((json['relationships'] as Array<any>).map(CodeGraphRelationshipFromJSON)),
    };
}

export function SupermodelIRGraphToJSON(value?: SupermodelIRGraph | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'nodes': ((value['nodes'] as Array<any>).map(CodeGraphNodeToJSON)),
        'relationships': ((value['relationships'] as Array<any>).map(CodeGraphRelationshipToJSON)),
    };
}

