/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.4.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SupermodelIRGraph } from './SupermodelIRGraph';
import {
    SupermodelIRGraphFromJSON,
    SupermodelIRGraphFromJSONTyped,
    SupermodelIRGraphToJSON,
} from './SupermodelIRGraph';
import type { SupermodelArtifact } from './SupermodelArtifact';
import {
    SupermodelArtifactFromJSON,
    SupermodelArtifactFromJSONTyped,
    SupermodelArtifactToJSON,
} from './SupermodelArtifact';

/**
 * 
 * @export
 * @interface SupermodelIR
 */
export interface SupermodelIR {
    /**
     * Repository slug the IR was generated from.
     * @type {string}
     * @memberof SupermodelIR
     */
    repo: string;
    /**
     * Version identifier for the IR content.
     * @type {string}
     * @memberof SupermodelIR
     */
    version: string;
    /**
     * Version of the IR schema.
     * @type {string}
     * @memberof SupermodelIR
     */
    schemaVersion: string;
    /**
     * Timestamp when the IR was generated.
     * @type {Date}
     * @memberof SupermodelIR
     */
    generatedAt: Date;
    /**
     * High-level metadata and summary insights including filesProcessed, classes, functions, types, primaryLanguage, and domains count.
     * @type {{ [key: string]: any; }}
     * @memberof SupermodelIR
     */
    summary?: { [key: string]: any; };
    /**
     * 
     * @type {SupermodelIRGraph}
     * @memberof SupermodelIR
     */
    graph: SupermodelIRGraph;
    /**
     * Per-source statistics and metadata for parse graph, call graph, and domain classification.
     * @type {Array<SupermodelArtifact>}
     * @memberof SupermodelIR
     */
    artifacts?: Array<SupermodelArtifact>;
}

/**
 * Check if a given object implements the SupermodelIR interface.
 */
export function instanceOfSupermodelIR(value: object): value is SupermodelIR {
    if (!('repo' in value) || value['repo'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('schemaVersion' in value) || value['schemaVersion'] === undefined) return false;
    if (!('generatedAt' in value) || value['generatedAt'] === undefined) return false;
    if (!('graph' in value) || value['graph'] === undefined) return false;
    return true;
}

export function SupermodelIRFromJSON(json: any): SupermodelIR {
    return SupermodelIRFromJSONTyped(json, false);
}

export function SupermodelIRFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupermodelIR {
    if (json == null) {
        return json;
    }
    return {
        
        'repo': json['repo'],
        'version': json['version'],
        'schemaVersion': json['schemaVersion'],
        'generatedAt': (new Date(json['generatedAt'])),
        'summary': json['summary'] == null ? undefined : json['summary'],
        'graph': SupermodelIRGraphFromJSON(json['graph']),
        'artifacts': json['artifacts'] == null ? undefined : ((json['artifacts'] as Array<any>).map(SupermodelArtifactFromJSON)),
    };
}

export function SupermodelIRToJSON(value?: SupermodelIR | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'repo': value['repo'],
        'version': value['version'],
        'schemaVersion': value['schemaVersion'],
        'generatedAt': ((value['generatedAt']).toISOString()),
        'summary': value['summary'],
        'graph': SupermodelIRGraphToJSON(value['graph']),
        'artifacts': value['artifacts'] == null ? undefined : ((value['artifacts'] as Array<any>).map(SupermodelArtifactToJSON)),
    };
}

