/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Summary statistics for the test coverage map analysis.
 * @export
 * @interface TestCoverageMapMetadata
 */
export interface TestCoverageMapMetadata {
    /**
     * Total number of files in the repository.
     * @type {number}
     * @memberof TestCoverageMapMetadata
     */
    totalFiles: number;
    /**
     * Number of files identified as test files.
     * @type {number}
     * @memberof TestCoverageMapMetadata
     */
    testFiles: number;
    /**
     * Number of non-test (production) files.
     * @type {number}
     * @memberof TestCoverageMapMetadata
     */
    productionFiles: number;
    /**
     * Total number of functions in production files.
     * @type {number}
     * @memberof TestCoverageMapMetadata
     */
    totalFunctions: number;
    /**
     * Number of production functions reachable from test functions.
     * @type {number}
     * @memberof TestCoverageMapMetadata
     */
    testedFunctions: number;
    /**
     * Number of production functions not reachable from any test function.
     * @type {number}
     * @memberof TestCoverageMapMetadata
     */
    untestedFunctions: number;
    /**
     * Percentage of production functions with test coverage.
     * @type {number}
     * @memberof TestCoverageMapMetadata
     */
    coveragePercentage: number;
    /**
     * Method used for analysis.
     * @type {string}
     * @memberof TestCoverageMapMetadata
     */
    analysisMethod: string;
    /**
     * Timestamp when analysis started.
     * @type {Date}
     * @memberof TestCoverageMapMetadata
     */
    analysisStartTime?: Date;
    /**
     * Timestamp when analysis completed.
     * @type {Date}
     * @memberof TestCoverageMapMetadata
     */
    analysisEndTime?: Date;
}

/**
 * Check if a given object implements the TestCoverageMapMetadata interface.
 */
export function instanceOfTestCoverageMapMetadata(value: object): value is TestCoverageMapMetadata {
    if (!('totalFiles' in value) || value['totalFiles'] === undefined) return false;
    if (!('testFiles' in value) || value['testFiles'] === undefined) return false;
    if (!('productionFiles' in value) || value['productionFiles'] === undefined) return false;
    if (!('totalFunctions' in value) || value['totalFunctions'] === undefined) return false;
    if (!('testedFunctions' in value) || value['testedFunctions'] === undefined) return false;
    if (!('untestedFunctions' in value) || value['untestedFunctions'] === undefined) return false;
    if (!('coveragePercentage' in value) || value['coveragePercentage'] === undefined) return false;
    if (!('analysisMethod' in value) || value['analysisMethod'] === undefined) return false;
    return true;
}

export function TestCoverageMapMetadataFromJSON(json: any): TestCoverageMapMetadata {
    return TestCoverageMapMetadataFromJSONTyped(json, false);
}

export function TestCoverageMapMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestCoverageMapMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'totalFiles': json['totalFiles'],
        'testFiles': json['testFiles'],
        'productionFiles': json['productionFiles'],
        'totalFunctions': json['totalFunctions'],
        'testedFunctions': json['testedFunctions'],
        'untestedFunctions': json['untestedFunctions'],
        'coveragePercentage': json['coveragePercentage'],
        'analysisMethod': json['analysisMethod'],
        'analysisStartTime': json['analysisStartTime'] == null ? undefined : (new Date(json['analysisStartTime'])),
        'analysisEndTime': json['analysisEndTime'] == null ? undefined : (new Date(json['analysisEndTime'])),
    };
}

export function TestCoverageMapMetadataToJSON(value?: TestCoverageMapMetadata | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'totalFiles': value['totalFiles'],
        'testFiles': value['testFiles'],
        'productionFiles': value['productionFiles'],
        'totalFunctions': value['totalFunctions'],
        'testedFunctions': value['testedFunctions'],
        'untestedFunctions': value['untestedFunctions'],
        'coveragePercentage': value['coveragePercentage'],
        'analysisMethod': value['analysisMethod'],
        'analysisStartTime': value['analysisStartTime'] == null ? undefined : ((value['analysisStartTime']).toISOString()),
        'analysisEndTime': value['analysisEndTime'] == null ? undefined : ((value['analysisEndTime']).toISOString()),
    };
}

