/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A sibling function in the same file that has test coverage.
 * @export
 * @interface TestedSibling
 */
export interface TestedSibling {
    /**
     * Name of the tested sibling function.
     * @type {string}
     * @memberof TestedSibling
     */
    name: string;
    /**
     * Line number where the sibling function is declared.
     * @type {number}
     * @memberof TestedSibling
     */
    line: number;
    /**
     * Test files that cover this sibling function.
     * @type {Array<string>}
     * @memberof TestedSibling
     */
    testFiles: Array<string>;
}

/**
 * Check if a given object implements the TestedSibling interface.
 */
export function instanceOfTestedSibling(value: object): value is TestedSibling {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('line' in value) || value['line'] === undefined) return false;
    if (!('testFiles' in value) || value['testFiles'] === undefined) return false;
    return true;
}

export function TestedSiblingFromJSON(json: any): TestedSibling {
    return TestedSiblingFromJSONTyped(json, false);
}

export function TestedSiblingFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestedSibling {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'line': json['line'],
        'testFiles': json['testFiles'],
    };
}

export function TestedSiblingToJSON(value?: TestedSibling | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'line': value['line'],
        'testFiles': value['testFiles'],
    };
}

