/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Information about a detected test file.
 * @export
 * @interface TestFileInfo
 */
export interface TestFileInfo {
    /**
     * File path relative to repository root.
     * @type {string}
     * @memberof TestFileInfo
     */
    file: string;
    /**
     * Number of test functions defined in this file.
     * @type {number}
     * @memberof TestFileInfo
     */
    testFunctions: number;
    /**
     * Number of unique production functions covered by tests in this file.
     * @type {number}
     * @memberof TestFileInfo
     */
    productionFunctionsCovered: number;
    /**
     * Number of unique production files covered by tests in this file.
     * @type {number}
     * @memberof TestFileInfo
     */
    productionFilesCovered: number;
}

/**
 * Check if a given object implements the TestFileInfo interface.
 */
export function instanceOfTestFileInfo(value: object): value is TestFileInfo {
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('testFunctions' in value) || value['testFunctions'] === undefined) return false;
    if (!('productionFunctionsCovered' in value) || value['productionFunctionsCovered'] === undefined) return false;
    if (!('productionFilesCovered' in value) || value['productionFilesCovered'] === undefined) return false;
    return true;
}

export function TestFileInfoFromJSON(json: any): TestFileInfo {
    return TestFileInfoFromJSONTyped(json, false);
}

export function TestFileInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestFileInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'],
        'testFunctions': json['testFunctions'],
        'productionFunctionsCovered': json['productionFunctionsCovered'],
        'productionFilesCovered': json['productionFilesCovered'],
    };
}

export function TestFileInfoToJSON(value?: TestFileInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file': value['file'],
        'testFunctions': value['testFunctions'],
        'productionFunctionsCovered': value['productionFunctionsCovered'],
        'productionFilesCovered': value['productionFilesCovered'],
    };
}

