/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A production function reachable from at least one test function.
 * @export
 * @interface TestedFunction
 */
export interface TestedFunction {
    /**
     * File path relative to repository root.
     * @type {string}
     * @memberof TestedFunction
     */
    file: string;
    /**
     * Name of the function or method.
     * @type {string}
     * @memberof TestedFunction
     */
    name: string;
    /**
     * Line number where the function is declared.
     * @type {number}
     * @memberof TestedFunction
     */
    line: number;
    /**
     * Type of code element.
     * @type {string}
     * @memberof TestedFunction
     */
    type: TestedFunctionTypeEnum;
    /**
     * Test files that cover this function (directly or transitively).
     * @type {Array<string>}
     * @memberof TestedFunction
     */
    testFiles: Array<string>;
    /**
     * Number of test functions that directly call this function.
     * @type {number}
     * @memberof TestedFunction
     */
    directTestCallers: number;
    /**
     * Number of test functions that transitively reach this function.
     * @type {number}
     * @memberof TestedFunction
     */
    transitiveTestCallers: number;
}


/**
 * @export
 */
export const TestedFunctionTypeEnum = {
    Function: 'function',
    Class: 'class',
    Method: 'method',
    Interface: 'interface',
    Type: 'type',
    Variable: 'variable',
    Constant: 'constant'
} as const;
export type TestedFunctionTypeEnum = typeof TestedFunctionTypeEnum[keyof typeof TestedFunctionTypeEnum];


/**
 * Check if a given object implements the TestedFunction interface.
 */
export function instanceOfTestedFunction(value: object): value is TestedFunction {
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('line' in value) || value['line'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('testFiles' in value) || value['testFiles'] === undefined) return false;
    if (!('directTestCallers' in value) || value['directTestCallers'] === undefined) return false;
    if (!('transitiveTestCallers' in value) || value['transitiveTestCallers'] === undefined) return false;
    return true;
}

export function TestedFunctionFromJSON(json: any): TestedFunction {
    return TestedFunctionFromJSONTyped(json, false);
}

export function TestedFunctionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestedFunction {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'],
        'name': json['name'],
        'line': json['line'],
        'type': json['type'],
        'testFiles': json['testFiles'],
        'directTestCallers': json['directTestCallers'],
        'transitiveTestCallers': json['transitiveTestCallers'],
    };
}

export function TestedFunctionToJSON(value?: TestedFunction | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file': value['file'],
        'name': value['name'],
        'line': value['line'],
        'type': value['type'],
        'testFiles': value['testFiles'],
        'directTestCallers': value['directTestCallers'],
        'transitiveTestCallers': value['transitiveTestCallers'],
    };
}

