/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UntestedFunction } from './UntestedFunction';
import {
    UntestedFunctionFromJSON,
    UntestedFunctionFromJSONTyped,
    UntestedFunctionToJSON,
} from './UntestedFunction';
import type { CoverageByDomain } from './CoverageByDomain';
import {
    CoverageByDomainFromJSON,
    CoverageByDomainFromJSONTyped,
    CoverageByDomainToJSON,
} from './CoverageByDomain';
import type { CoverageByFile } from './CoverageByFile';
import {
    CoverageByFileFromJSON,
    CoverageByFileFromJSONTyped,
    CoverageByFileToJSON,
} from './CoverageByFile';
import type { TestCoverageMapMetadata } from './TestCoverageMapMetadata';
import {
    TestCoverageMapMetadataFromJSON,
    TestCoverageMapMetadataFromJSONTyped,
    TestCoverageMapMetadataToJSON,
} from './TestCoverageMapMetadata';
import type { TestedFunction } from './TestedFunction';
import {
    TestedFunctionFromJSON,
    TestedFunctionFromJSONTyped,
    TestedFunctionToJSON,
} from './TestedFunction';
import type { TestFileInfo } from './TestFileInfo';
import {
    TestFileInfoFromJSON,
    TestFileInfoFromJSONTyped,
    TestFileInfoToJSON,
} from './TestFileInfo';

/**
 * Test coverage map result identifying tested and untested functions via static call graph reachability from test files.
 * @export
 * @interface TestCoverageMapResponse
 */
export interface TestCoverageMapResponse {
    /**
     * 
     * @type {TestCoverageMapMetadata}
     * @memberof TestCoverageMapResponse
     */
    metadata: TestCoverageMapMetadata;
    /**
     * Production functions with no test coverage (not reachable from any test function).
     * @type {Array<UntestedFunction>}
     * @memberof TestCoverageMapResponse
     */
    untestedFunctions: Array<UntestedFunction>;
    /**
     * Production functions with test coverage (reachable from at least one test function).
     * @type {Array<TestedFunction>}
     * @memberof TestCoverageMapResponse
     */
    testedFunctions: Array<TestedFunction>;
    /**
     * Detected test files with coverage statistics.
     * @type {Array<TestFileInfo>}
     * @memberof TestCoverageMapResponse
     */
    testFiles: Array<TestFileInfo>;
    /**
     * Coverage breakdown by domain classification.
     * @type {Array<CoverageByDomain>}
     * @memberof TestCoverageMapResponse
     */
    coverageByDomain?: Array<CoverageByDomain>;
    /**
     * Coverage breakdown by production file.
     * @type {Array<CoverageByFile>}
     * @memberof TestCoverageMapResponse
     */
    coverageByFile: Array<CoverageByFile>;
}

/**
 * Check if a given object implements the TestCoverageMapResponse interface.
 */
export function instanceOfTestCoverageMapResponse(value: object): value is TestCoverageMapResponse {
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('untestedFunctions' in value) || value['untestedFunctions'] === undefined) return false;
    if (!('testedFunctions' in value) || value['testedFunctions'] === undefined) return false;
    if (!('testFiles' in value) || value['testFiles'] === undefined) return false;
    if (!('coverageByFile' in value) || value['coverageByFile'] === undefined) return false;
    return true;
}

export function TestCoverageMapResponseFromJSON(json: any): TestCoverageMapResponse {
    return TestCoverageMapResponseFromJSONTyped(json, false);
}

export function TestCoverageMapResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestCoverageMapResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': TestCoverageMapMetadataFromJSON(json['metadata']),
        'untestedFunctions': ((json['untestedFunctions'] as Array<any>).map(UntestedFunctionFromJSON)),
        'testedFunctions': ((json['testedFunctions'] as Array<any>).map(TestedFunctionFromJSON)),
        'testFiles': ((json['testFiles'] as Array<any>).map(TestFileInfoFromJSON)),
        'coverageByDomain': json['coverageByDomain'] == null ? undefined : ((json['coverageByDomain'] as Array<any>).map(CoverageByDomainFromJSON)),
        'coverageByFile': ((json['coverageByFile'] as Array<any>).map(CoverageByFileFromJSON)),
    };
}

export function TestCoverageMapResponseToJSON(value?: TestCoverageMapResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'metadata': TestCoverageMapMetadataToJSON(value['metadata']),
        'untestedFunctions': ((value['untestedFunctions'] as Array<any>).map(UntestedFunctionToJSON)),
        'testedFunctions': ((value['testedFunctions'] as Array<any>).map(TestedFunctionToJSON)),
        'testFiles': ((value['testFiles'] as Array<any>).map(TestFileInfoToJSON)),
        'coverageByDomain': value['coverageByDomain'] == null ? undefined : ((value['coverageByDomain'] as Array<any>).map(CoverageByDomainToJSON)),
        'coverageByFile': ((value['coverageByFile'] as Array<any>).map(CoverageByFileToJSON)),
    };
}

