/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TestCoverageMapResponse } from './TestCoverageMapResponse';
import {
    TestCoverageMapResponseFromJSON,
    TestCoverageMapResponseFromJSONTyped,
    TestCoverageMapResponseToJSON,
} from './TestCoverageMapResponse';

/**
 * 
 * @export
 * @interface TestCoverageMapResponseAsync
 */
export interface TestCoverageMapResponseAsync {
    /**
     * Current status of the job.
     * @type {string}
     * @memberof TestCoverageMapResponseAsync
     */
    status: TestCoverageMapResponseAsyncStatusEnum;
    /**
     * Unique identifier for the job.
     * @type {string}
     * @memberof TestCoverageMapResponseAsync
     */
    jobId: string;
    /**
     * Recommended seconds to wait before polling again.
     * @type {number}
     * @memberof TestCoverageMapResponseAsync
     */
    retryAfter?: number;
    /**
     * Error message (present when status is failed).
     * @type {string}
     * @memberof TestCoverageMapResponseAsync
     */
    error?: string;
    /**
     * 
     * @type {TestCoverageMapResponse}
     * @memberof TestCoverageMapResponseAsync
     */
    result?: TestCoverageMapResponse;
}


/**
 * @export
 */
export const TestCoverageMapResponseAsyncStatusEnum = {
    Pending: 'pending',
    Processing: 'processing',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type TestCoverageMapResponseAsyncStatusEnum = typeof TestCoverageMapResponseAsyncStatusEnum[keyof typeof TestCoverageMapResponseAsyncStatusEnum];


/**
 * Check if a given object implements the TestCoverageMapResponseAsync interface.
 */
export function instanceOfTestCoverageMapResponseAsync(value: object): value is TestCoverageMapResponseAsync {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    return true;
}

export function TestCoverageMapResponseAsyncFromJSON(json: any): TestCoverageMapResponseAsync {
    return TestCoverageMapResponseAsyncFromJSONTyped(json, false);
}

export function TestCoverageMapResponseAsyncFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestCoverageMapResponseAsync {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'jobId': json['jobId'],
        'retryAfter': json['retryAfter'] == null ? undefined : json['retryAfter'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : TestCoverageMapResponseFromJSON(json['result']),
    };
}

export function TestCoverageMapResponseAsyncToJSON(value?: TestCoverageMapResponseAsync | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'jobId': value['jobId'],
        'retryAfter': value['retryAfter'],
        'error': value['error'],
        'result': TestCoverageMapResponseToJSON(value['result']),
    };
}

