/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.6.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnassignedFunction
 */
export interface UnassignedFunction {
    /**
     * Function that could not be assigned
     * @type {string}
     * @memberof UnassignedFunction
     */
    functionId: string;
    /**
     * Reason it was left unassigned
     * @type {string}
     * @memberof UnassignedFunction
     */
    reason: string;
}

/**
 * Check if a given object implements the UnassignedFunction interface.
 */
export function instanceOfUnassignedFunction(value: object): value is UnassignedFunction {
    if (!('functionId' in value) || value['functionId'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function UnassignedFunctionFromJSON(json: any): UnassignedFunction {
    return UnassignedFunctionFromJSONTyped(json, false);
}

export function UnassignedFunctionFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnassignedFunction {
    if (json == null) {
        return json;
    }
    return {
        
        'functionId': json['functionId'],
        'reason': json['reason'],
    };
}

export function UnassignedFunctionToJSON(value?: UnassignedFunction | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'functionId': value['functionId'],
        'reason': value['reason'],
    };
}

