/* tslint:disable */
/* eslint-disable */
/**
 * Supermodel
 * Code Graphing & Analysis API
 *
 * The version of the OpenAPI document: 0.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TestedSibling } from './TestedSibling';
import {
    TestedSiblingFromJSON,
    TestedSiblingFromJSONTyped,
    TestedSiblingToJSON,
} from './TestedSibling';
import type { NearestTestedCaller } from './NearestTestedCaller';
import {
    NearestTestedCallerFromJSON,
    NearestTestedCallerFromJSONTyped,
    NearestTestedCallerToJSON,
} from './NearestTestedCaller';

/**
 * A production function with no test coverage.
 * @export
 * @interface UntestedFunction
 */
export interface UntestedFunction {
    /**
     * File path relative to repository root.
     * @type {string}
     * @memberof UntestedFunction
     */
    file: string;
    /**
     * Name of the function or method.
     * @type {string}
     * @memberof UntestedFunction
     */
    name: string;
    /**
     * Line number where the function is declared.
     * @type {number}
     * @memberof UntestedFunction
     */
    line: number;
    /**
     * Type of code element.
     * @type {string}
     * @memberof UntestedFunction
     */
    type: UntestedFunctionTypeEnum;
    /**
     * Confidence level of the untested classification.
     * @type {string}
     * @memberof UntestedFunction
     */
    confidence: UntestedFunctionConfidenceEnum;
    /**
     * Explanation of why this function is classified as untested.
     * @type {string}
     * @memberof UntestedFunction
     */
    reason: string;
    /**
     * 
     * @type {NearestTestedCaller}
     * @memberof UntestedFunction
     */
    nearestTestedCaller?: NearestTestedCaller;
    /**
     * The test file that covers the most sibling functions in the same production file. This is the recommended file in which to add a test for this untested function.
     * @type {string}
     * @memberof UntestedFunction
     */
    suggestedTestFile?: string;
    /**
     * Other functions in the same file that ARE tested, along with which test files cover them. Use this to see existing test patterns you can follow.
     * @type {Array<TestedSibling>}
     * @memberof UntestedFunction
     */
    testedSiblings?: Array<TestedSibling>;
}


/**
 * @export
 */
export const UntestedFunctionTypeEnum = {
    Function: 'function',
    Class: 'class',
    Method: 'method',
    Interface: 'interface',
    Type: 'type',
    Variable: 'variable',
    Constant: 'constant'
} as const;
export type UntestedFunctionTypeEnum = typeof UntestedFunctionTypeEnum[keyof typeof UntestedFunctionTypeEnum];

/**
 * @export
 */
export const UntestedFunctionConfidenceEnum = {
    High: 'high',
    Medium: 'medium',
    Low: 'low'
} as const;
export type UntestedFunctionConfidenceEnum = typeof UntestedFunctionConfidenceEnum[keyof typeof UntestedFunctionConfidenceEnum];


/**
 * Check if a given object implements the UntestedFunction interface.
 */
export function instanceOfUntestedFunction(value: object): value is UntestedFunction {
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('line' in value) || value['line'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('confidence' in value) || value['confidence'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function UntestedFunctionFromJSON(json: any): UntestedFunction {
    return UntestedFunctionFromJSONTyped(json, false);
}

export function UntestedFunctionFromJSONTyped(json: any, ignoreDiscriminator: boolean): UntestedFunction {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'],
        'name': json['name'],
        'line': json['line'],
        'type': json['type'],
        'confidence': json['confidence'],
        'reason': json['reason'],
        'nearestTestedCaller': json['nearestTestedCaller'] == null ? undefined : NearestTestedCallerFromJSON(json['nearestTestedCaller']),
        'suggestedTestFile': json['suggestedTestFile'] == null ? undefined : json['suggestedTestFile'],
        'testedSiblings': json['testedSiblings'] == null ? undefined : ((json['testedSiblings'] as Array<any>).map(TestedSiblingFromJSON)),
    };
}

export function UntestedFunctionToJSON(value?: UntestedFunction | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file': value['file'],
        'name': value['name'],
        'line': value['line'],
        'type': value['type'],
        'confidence': value['confidence'],
        'reason': value['reason'],
        'nearestTestedCaller': NearestTestedCallerToJSON(value['nearestTestedCaller']),
        'suggestedTestFile': value['suggestedTestFile'],
        'testedSiblings': value['testedSiblings'] == null ? undefined : ((value['testedSiblings'] as Array<any>).map(TestedSiblingToJSON)),
    };
}

